/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AdminLogin;

import java.awt.event.ItemEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import Batch.BatchUI;
import Course.Course;
import Subject.Subject;
import Teacher.Teacher;
import Payment.Payment;
import ITStudent.StdFirstPage_View_IT;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;



public class AdminPanel extends javax.swing.JFrame {

    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        initComponents();
         Image ic=new ImageIcon(this.getClass().getResource("/jpro.jpg")).getImage();
        this.setIconImage(ic);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPane = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtuname = new javax.swing.JTextField();
        btnLog = new javax.swing.JButton();
        txtpwd = new javax.swing.JPasswordField();
        jHide = new javax.swing.JLabel();
        jShow = new javax.swing.JLabel();
        jbackk = new javax.swing.JLabel();
        pChoose = new javax.swing.JPanel();
        logoutpane = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lbluid = new javax.swing.JLabel();
        ename = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Payment = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        Subject = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Batch = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Teacher = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Course = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Student = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JPRO InfoHub Course Management System");
        setName("JPro Course Information Management System"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginPane.setBackground(new java.awt.Color(0, 0, 0));
        loginPane.setLayout(null);

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 0, 0));
        jLabel16.setText("Password  :");
        loginPane.add(jLabel16);
        jLabel16.setBounds(380, 390, 90, 40);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/girlpf-removebg-preview.png"))); // NOI18N
        loginPane.add(jLabel17);
        jLabel17.setBounds(180, 300, 170, 170);

        jPanel9.setBackground(new java.awt.Color(204, 204, 204,80
        ));
        jPanel9.setForeground(new java.awt.Color(204, 204, 204));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/JLogo.png"))); // NOI18N
        jPanel9.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Agency FB", 1, 60)); // NOI18N
        jLabel19.setText("J-Pro");
        jPanel9.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 145, 60));

        jLabel20.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel20.setText("Vocational School\n\n");
        jPanel9.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 200, 30));

        jLabel21.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel21.setText("IT & JAPANESE LANGUAGE");
        jPanel9.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 210, 43));

        loginPane.add(jPanel9);
        jPanel9.setBounds(0, 0, 1100, 200);

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 0, 0));
        jLabel22.setText("User_Name   :");
        loginPane.add(jLabel22);
        jLabel22.setBounds(360, 330, 103, 40);

        txtuname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtuname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtunameActionPerformed(evt);
            }
        });
        loginPane.add(txtuname);
        txtuname.setBounds(490, 340, 180, 30);

        btnLog.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLog.setText("LOGIN");
        btnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogActionPerformed(evt);
            }
        });
        loginPane.add(btnLog);
        btnLog.setBounds(530, 450, 100, 28);
        loginPane.add(txtpwd);
        txtpwd.setBounds(490, 400, 180, 30);

        jHide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eye_hide.png"))); // NOI18N
        jHide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jHideMouseClicked(evt);
            }
        });
        loginPane.add(jHide);
        jHide.setBounds(680, 390, 70, 40);

        jShow.setBackground(new java.awt.Color(0, 0, 0,18));
        jShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eye.png"))); // NOI18N
        jShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jShowMouseClicked(evt);
            }
        });
        loginPane.add(jShow);
        jShow.setBounds(680, 390, 50, 40);

        jbackk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/itjpbg.jpg"))); // NOI18N
        jbackk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        loginPane.add(jbackk);
        jbackk.setBounds(0, 0, 1100, 690);

        getContentPane().add(loginPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 690));

        pChoose.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutpane.setBackground(new java.awt.Color(255, 255, 255));
        logoutpane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        logoutpane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 0, 0));
        jLabel14.setText("Name :");
        logoutpane.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, 20));

        jPanel2.setBackground(new java.awt.Color(204, 0, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setBackground(new java.awt.Color(204, 204, 204));
        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Log Out");
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 60, 50));

        logoutpane.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 190, 50));

        jPanel10.setBackground(new java.awt.Color(204, 0, 51));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/staffadmin-removebg-preview.png"))); // NOI18N
        jPanel10.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 130, 140));

        logoutpane.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 150));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 0, 0));
        jLabel15.setText("UserID :");
        logoutpane.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 60, -1));

        lbluid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbluid.setForeground(new java.awt.Color(255, 0, 0));
        logoutpane.add(lbluid, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 80, 20));

        ename.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ename.setForeground(new java.awt.Color(255, 0, 0));
        logoutpane.add(ename, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 110, 20));

        pChoose.add(logoutpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 130, 180, 560));

        jPanel8.setBackground(new java.awt.Color(0, 0, 0,1));
        jPanel8.setPreferredSize(new java.awt.Dimension(190, 200));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Payment");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 170, 30));

        Payment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Payment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Payment.png"))); // NOI18N
        Payment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Payment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PaymentMouseClicked(evt);
            }
        });
        jPanel8.add(Payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 170));

        pChoose.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 440, 190, 200));

        jPanel7.setBackground(new java.awt.Color(0, 0, 0,1));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Subject.setForeground(new java.awt.Color(102, 0, 0));
        Subject.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Subject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Subject.png"))); // NOI18N
        Subject.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Subject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubjectMouseClicked(evt);
            }
        });
        jPanel7.add(Subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 170));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Subject");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 180, 30));

        pChoose.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 190, 200));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0,1));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Batch");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 160, 40));

        Batch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Batch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Batch.png"))); // NOI18N
        Batch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Batch.setPreferredSize(new java.awt.Dimension(240, 170));
        Batch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BatchMouseClicked(evt);
            }
        });
        jPanel5.add(Batch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 180));

        pChoose.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, 190, 200));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0,1));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Teacher");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 190, 30));

        Teacher.setBackground(new java.awt.Color(0, 0, 0));
        Teacher.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Teacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Teacher.png"))); // NOI18N
        Teacher.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Teacher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TeacherMouseClicked(evt);
            }
        });
        jPanel6.add(Teacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 180));

        pChoose.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 190, 200));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0,1));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Course.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Course.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Course.png"))); // NOI18N
        Course.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CourseMouseClicked(evt);
            }
        });
        jPanel4.add(Course, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 170));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Course");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 190, -1));

        pChoose.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 190, 200));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0,1));
        jPanel3.setMinimumSize(new java.awt.Dimension(190, 200));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Student.setBackground(new java.awt.Color(0, 0, 0));
        Student.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Student.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Student.png"))); // NOI18N
        Student.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Student.setPreferredSize(new java.awt.Dimension(240, 170));
        Student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudentMouseClicked(evt);
            }
        });
        jPanel3.add(Student, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 170));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Student");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 190, 30));

        pChoose.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 190, 200));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204,80
        ));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 60)); // NOI18N
        jLabel2.setText("Info-HUB");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 430, 90));

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel3.setText("Course Managment System");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/JLogo.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 160, 180));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Profile-removebg-preview.png"))); // NOI18N
        jLabel11.setText("jLabel11");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 30, 50, 50));

        pChoose.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 180));
        pChoose.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 640));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/admimglamp.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        pChoose.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 690));

        getContentPane().add(pChoose, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentMouseClicked
        dispose();
        StdFirstPage_View_IT fp = new StdFirstPage_View_IT();
       fp.setVisible(true);
       fp.loadtable();
    }//GEN-LAST:event_StudentMouseClicked

    private void CourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CourseMouseClicked
        dispose();
        Course c = new Course();
        c.setVisible(true);
        c.loadcoursetable();
    }//GEN-LAST:event_CourseMouseClicked

    private void BatchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BatchMouseClicked
         dispose();
        BatchUI bui = new BatchUI();
        bui.setVisible(true);
        try {
            bui.loadTableBatch();
        } catch (SQLException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BatchMouseClicked

    private void TeacherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TeacherMouseClicked
       dispose();
        Teacher t = new Teacher();
       t.setVisible(true);
       t.loadtable();
    }//GEN-LAST:event_TeacherMouseClicked

    private void SubjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubjectMouseClicked
        dispose();
        Subject sub = new Subject();
        sub.setVisible(true);
        sub.loadSubjecttable();
    }//GEN-LAST:event_SubjectMouseClicked

    private void PaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaymentMouseClicked
       dispose();
        Payment pay = new Payment();
        pay.setVisible(true);
        pay.loadPaymet();
        
    }//GEN-LAST:event_PaymentMouseClicked
 
    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
     
       int choice=JOptionPane.showConfirmDialog(null, "Do you really want to logout From your Account","Confirm Message",JOptionPane.INFORMATION_MESSAGE);
       if(choice==JOptionPane.YES_OPTION){
        loginPane.setVisible(true);
     pChoose.setVisible(false);
     txtuname.setText("");
     txtpwd.setText("");}
       else if(choice==JOptionPane.NO_OPTION){
           pChoose.setVisible(true);
           logoutpane.setVisible(false);
       }
        else if(choice==JOptionPane.CANCEL_OPTION){
           pChoose.setVisible(true);
           logoutpane.setVisible(false);
       }

    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
            logoutpane.setVisible(true);
   
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        logoutpane.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void txtunameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtunameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtunameActionPerformed

    private void btnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogActionPerformed
    try {
            int uid=new userDAO().checkUser(txtuname.getText(),txtpwd.getText());
            if(uid==0){
                JOptionPane.showMessageDialog(null, "UserName and Password doesn't match","Login Error",JOptionPane.ERROR_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "Login Successfully");
                pChoose.setVisible(true);
                loginPane.setVisible(false);
                logoutpane.setVisible(false);
                String nm=txtuname.getText();
                userDAO udao=new userDAO();
                user u=udao.returnAllDataToTextField(nm);
                ename.setText(u.getEname());
                lbluid.setText(String.valueOf(u.getUid()));
               Course cc=new Course();
               cc.lblidcall.setText(String.valueOf(u.getUid()));
               
            }

        } catch (SQLException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLogActionPerformed

    private void jHideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHideMouseClicked
        jHide.setVisible(false);
        jShow.setVisible(true);
        //        jHide.setVisible(false);
        txtpwd.setEchoChar((char)0);
    }//GEN-LAST:event_jHideMouseClicked

    private void jShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jShowMouseClicked
        jShow.setVisible(false);
        jHide.setVisible(true);
        txtpwd.setEchoChar('\u25cf');
    }//GEN-LAST:event_jShowMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Batch;
    private javax.swing.JLabel Course;
    private javax.swing.JLabel Payment;
    private javax.swing.JLabel Student;
    private javax.swing.JLabel Subject;
    private javax.swing.JLabel Teacher;
    public javax.swing.JButton btnLog;
    public javax.swing.JLabel ename;
    private javax.swing.JLabel jHide;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel jShow;
    private javax.swing.JLabel jbackk;
    public javax.swing.JLabel lbluid;
    public javax.swing.JPanel loginPane;
    public javax.swing.JPanel logoutpane;
    public javax.swing.JPanel pChoose;
    public javax.swing.JPasswordField txtpwd;
    public javax.swing.JTextField txtuname;
    // End of variables declaration//GEN-END:variables




}
