/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Payment;

import Batch.BatchUI;
import Payment.PaymentDAO;
import Payment.Payment;
import Payment.PayData;
import java.awt.Image;
import java.sql.Date;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author shoto
 */
public class PaymentSlip extends javax.swing.JFrame {

    /**
     * Creates new form PaymentSlip
     */
    public PaymentSlip() {
        initComponents();
         Image ic=new ImageIcon(this.getClass().getResource("/jpro.jpg")).getImage();
        this.setIconImage(ic);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Backbtn = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtBmId = new javax.swing.JTextField();
        Sname = new javax.swing.JTextField();
        Ph_no = new javax.swing.JTextField();
        txtDisc = new javax.swing.JTextField();
        cbPmethod = new javax.swing.JComboBox<>();
        accname = new javax.swing.JTextField();
        paydesc = new javax.swing.JTextArea();
        Payremark = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnadd = new javax.swing.JButton();
        btncancle = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtAmt = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        dcSlipDate = new com.toedter.calendar.JDateChooser();
        txtDate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JPRO InfoHub Course Management System\\");
            setMinimumSize(new java.awt.Dimension(510, 700));
            getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jPanel2.setBackground(new java.awt.Color(153, 0, 0));
            jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jPanel1.setBackground(new java.awt.Color(255, 255, 255));
            jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jLabel1.setFont(new java.awt.Font("Agency FB", 1, 45)); // NOI18N
            jLabel1.setForeground(new java.awt.Color(153, 0, 0));
            jLabel1.setText("Slip");
            jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, -10, -1, 60));

            Backbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            Backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Back.png"))); // NOI18N
            Backbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            Backbtn.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    BackbtnMouseClicked(evt);
                }
            });
            jPanel1.add(Backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));

            jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 490, 50));

            getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 70));

            jPanel3.setBackground(new java.awt.Color(204, 204, 204));
            jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
            jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
            jLabel2.setForeground(new java.awt.Color(102, 0, 0));
            jLabel2.setText("Batch Mm ID");
            jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 30));

            jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
            jLabel4.setForeground(new java.awt.Color(102, 0, 0));
            jLabel4.setText("Phone No");
            jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

            jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
            jLabel6.setForeground(new java.awt.Color(102, 0, 0));
            jLabel6.setText("Payment Method");
            jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

            jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
            jLabel5.setForeground(new java.awt.Color(102, 0, 0));
            jLabel5.setText("Email");
            jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

            jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
            jLabel8.setForeground(new java.awt.Color(102, 0, 0));
            jLabel8.setText("Description");
            jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

            jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
            jLabel7.setForeground(new java.awt.Color(102, 0, 0));
            jLabel7.setText("Acc Name");
            jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

            jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
            jLabel9.setForeground(new java.awt.Color(102, 0, 0));
            jLabel9.setText("Remark");
            jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

            jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
            jLabel3.setForeground(new java.awt.Color(102, 0, 0));
            jLabel3.setText("Name");
            jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

            txtBmId.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    txtBmIdActionPerformed(evt);
                }
            });
            jPanel3.add(txtBmId, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 210, 30));
            jPanel3.add(Sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 210, 30));
            jPanel3.add(Ph_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 210, 30));

            txtDisc.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    txtDiscActionPerformed(evt);
                }
            });
            jPanel3.add(txtDisc, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 210, 30));

            cbPmethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KBZ Pay", "CB Pay", "Wave Money", "Bank Acc","Cash" }));
            jPanel3.add(cbPmethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 210, 30));
            jPanel3.add(accname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 210, 30));

            paydesc.setColumns(20);
            paydesc.setRows(5);
            jPanel3.add(paydesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 210, -1));
            jPanel3.add(Payremark, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, 210, 30));

            jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
            jLabel10.setForeground(new java.awt.Color(102, 0, 0));
            jLabel10.setText(":");
            jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 20, -1));

            jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
            jLabel11.setForeground(new java.awt.Color(102, 0, 0));
            jLabel11.setText(":");
            jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 20, -1));

            jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
            jLabel12.setForeground(new java.awt.Color(102, 0, 0));
            jLabel12.setText(":");
            jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 20, 30));

            jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
            jLabel13.setForeground(new java.awt.Color(102, 0, 0));
            jLabel13.setText(":");
            jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 20, -1));

            jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
            jLabel14.setForeground(new java.awt.Color(102, 0, 0));
            jLabel14.setText(":");
            jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, 20, -1));

            jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
            jLabel15.setForeground(new java.awt.Color(102, 0, 0));
            jLabel15.setText(":");
            jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 20, -1));

            jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
            jLabel16.setForeground(new java.awt.Color(102, 0, 0));
            jLabel16.setText(":");
            jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 20, -1));

            jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
            jLabel17.setForeground(new java.awt.Color(102, 0, 0));
            jLabel17.setText(":");
            jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 20, -1));

            btnadd.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
            btnadd.setForeground(new java.awt.Color(153, 0, 0));
            btnadd.setText("Add");
            btnadd.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnaddActionPerformed(evt);
                }
            });
            jPanel3.add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 580, 100, 40));

            btncancle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
            btncancle.setForeground(new java.awt.Color(153, 0, 0));
            btncancle.setText("Cancel");
            btncancle.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btncancleActionPerformed(evt);
                }
            });
            jPanel3.add(btncancle, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 580, 100, 40));

            jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
            jLabel18.setForeground(new java.awt.Color(102, 0, 0));
            jLabel18.setText("Amount");
            jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));
            jPanel3.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 210, 30));

            jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
            jLabel19.setForeground(new java.awt.Color(102, 0, 0));
            jLabel19.setText("Discount");
            jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));
            jPanel3.add(txtAmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 210, 30));

            jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
            jLabel20.setForeground(new java.awt.Color(102, 0, 0));
            jLabel20.setText("Date");
            jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 40, 30));

            jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
            jLabel21.setForeground(new java.awt.Color(102, 0, 0));
            jLabel21.setText(":");
            jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 20, -1));

            jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
            jLabel22.setForeground(new java.awt.Color(102, 0, 0));
            jLabel22.setText(":");
            jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 20, 30));

            jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
            jLabel23.setForeground(new java.awt.Color(102, 0, 0));
            jLabel23.setText(":");
            jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 20, -1));
            jPanel3.add(dcSlipDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 210, -1));
            jPanel3.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 210, -1));

            getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 510, 630));

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void txtBmIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBmIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBmIdActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed

            int bmid = Integer.parseInt(txtBmId.getText());
            Date payDate = new Date(dcSlipDate.getDate().getTime());
            String amt = txtAmt.getText();
            String disc = txtDisc.getText();
            String pmethod = cbPmethod.getSelectedItem().toString();
            String info = accname.getText();
            String desc = paydesc.getText();
            String remark = Payremark.getText();
            PayData payment = new PayData(0,bmid,payDate,amt,disc,pmethod,info,desc,remark);
            
            try {
            int choice = JOptionPane.showConfirmDialog(null, "Do you really want to update your payment data","Confirm Message",JOptionPane.INFORMATION_MESSAGE);
            if(choice==JOptionPane.YES_OPTION){
                new PaymentDAO().updatePaymentInfo(payment);
                JOptionPane.showMessageDialog(null, "Successfully updated to Payment");
                new Payment().loadPaymet();
                BatchUI bt = new BatchUI();
                bt.loadTablePayment();
               
                setVisible(false);
                
               
           }
	} catch (SQLException e1) {
            JOptionPane.showMessageDialog(null, e1.toString(),"DB Error",JOptionPane.ERROR_MESSAGE);
	}
            
         Slip s = new Slip();
         s.setVisible(true);
           
            
    }//GEN-LAST:event_btnaddActionPerformed

    private void BackbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackbtnMouseClicked
        Payment pay = new Payment();
       pay.setVisible(true);
       pay.loadPaymet();
    }//GEN-LAST:event_BackbtnMouseClicked

    private void txtDiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiscActionPerformed

    private void btncancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancleActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btncancleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentSlip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentSlip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentSlip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentSlip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentSlip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backbtn;
    public javax.swing.JTextField Payremark;
    public javax.swing.JTextField Ph_no;
    public javax.swing.JTextField Sname;
    public javax.swing.JTextField accname;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btncancle;
    public javax.swing.JComboBox<String> cbPmethod;
    public com.toedter.calendar.JDateChooser dcSlipDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JTextArea paydesc;
    public javax.swing.JTextField txtAmt;
    public javax.swing.JTextField txtBmId;
    public javax.swing.JTextField txtDate;
    public javax.swing.JTextField txtDisc;
    public javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
