/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package ITStudent;

import AdminLogin.AdminPanel;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class ITstdUpdate extends javax.swing.JFrame {

    private Connection con;
    public ITstdUpdate() {
        initComponents();
         Image ic=new ImageIcon(this.getClass().getResource("/jpro.jpg")).getImage();
        this.setIconImage(ic);
         try{
             con = DriverManager.getConnection("jdbc:mysql://localhost:3306/jpro_infohub","root","root");
        }
        catch(SQLException e){
         e.printStackTrace();
        }
            
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngGender = new javax.swing.ButtonGroup();
        btngReli = new javax.swing.ButtonGroup();
        btngNation = new javax.swing.ButtonGroup();
        Page1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        rdoFemaleU = new javax.swing.JRadioButton();
        rdoIslumU = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        rdoMaleU = new javax.swing.JRadioButton();
        rdoOtherU = new javax.swing.JRadioButton();
        rdoChristianU = new javax.swing.JRadioButton();
        rdoHinduU = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        rdoBuddishU = new javax.swing.JRadioButton();
        rdoMyanmarU = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        labHomeU1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labBackU1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtstdPhnoU = new javax.swing.JTextField();
        txtstdEmailU = new javax.swing.JTextField();
        txtstdTeleU = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnUpdate1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtstdIdU = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtstdNRCU = new javax.swing.JTextField();
        txtstdNameU = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lblupdateimg = new javax.swing.JLabel();
        txtstd_id = new javax.swing.JTextField();
        txtimgpath = new javax.swing.JTextField();
        btnbrowse = new javax.swing.JButton();
        txtdateu = new com.toedter.calendar.JDateChooser();
        btnNext1 = new javax.swing.JButton();
        btnClear1 = new javax.swing.JButton();
        Page2 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        txtPhnoRsU2 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        cboRSTypeU2 = new javax.swing.JComboBox<>();
        jLabel51 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaOccuU2 = new javax.swing.JTextArea();
        txtRSNameU3 = new javax.swing.JTextField();
        txtupstdid = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        labBackA2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jscrolRsA = new javax.swing.JScrollPane();
        jTableRsA = new javax.swing.JTable();
        btnNext2 = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        txtTownshipU2 = new javax.swing.JTextField();
        txtRegionU2 = new javax.swing.JTextField();
        txtCityU2 = new javax.swing.JTextField();
        btnUpdate2 = new javax.swing.JButton();
        btnClear2 = new javax.swing.JButton();
        Page3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtOrgA3 = new javax.swing.JTextField();
        txtDipoNameU3 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        cboDipoTypeU3 = new javax.swing.JComboBox<>();
        jLabel39 = new javax.swing.JLabel();
        txtFieldU3 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jscrolEDUU3 = new javax.swing.JScrollPane();
        jTableEDUU3 = new javax.swing.JTable();
        DateChFromU3 = new com.toedter.calendar.JDateChooser();
        DateChToU3 = new com.toedter.calendar.JDateChooser();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        labBackA3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnFinish3 = new javax.swing.JButton();
        btnUpdate3 = new javax.swing.JButton();
        btnClear3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JPRO InfoHub Course Management System");
        setMinimumSize(new java.awt.Dimension(1100, 690));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Page1.setBackground(new java.awt.Color(204, 204, 204));
        Page1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        Page1.setMinimumSize(new java.awt.Dimension(1100, 690));
        Page1.setPreferredSize(new java.awt.Dimension(1100, 690));
        Page1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setBackground(new java.awt.Color(153, 153, 153));
        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(153, 0, 0));
        jLabel29.setText("General Info");
        jPanel10.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 40));

        Page1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, 120, -1));

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 0, 0));
        jLabel15.setText("Nationality");
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 90, 20));

        btngGender.add(rdoFemaleU);
        rdoFemaleU.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdoFemaleU.setForeground(new java.awt.Color(102, 0, 0));
        rdoFemaleU.setText("Female");
        jPanel7.add(rdoFemaleU, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, 30));

        btngReli.add(rdoIslumU);
        rdoIslumU.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdoIslumU.setForeground(new java.awt.Color(102, 0, 0));
        rdoIslumU.setText("Islam");
        rdoIslumU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoIslumUActionPerformed(evt);
            }
        });
        jPanel7.add(rdoIslumU, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, -1, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 0, 0));
        jLabel18.setText("Gender");
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 80, 20));

        btngGender.add(rdoMaleU);
        rdoMaleU.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdoMaleU.setForeground(new java.awt.Color(102, 0, 0));
        rdoMaleU.setText("Male");
        rdoMaleU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoMaleUActionPerformed(evt);
            }
        });
        jPanel7.add(rdoMaleU, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, 30));

        btngNation.add(rdoOtherU);
        rdoOtherU.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdoOtherU.setForeground(new java.awt.Color(102, 0, 0));
        rdoOtherU.setText("Other");
        rdoOtherU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoOtherUActionPerformed(evt);
            }
        });
        jPanel7.add(rdoOtherU, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, 30));

        btngReli.add(rdoChristianU);
        rdoChristianU.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdoChristianU.setForeground(new java.awt.Color(102, 0, 0));
        rdoChristianU.setText("Christian");
        rdoChristianU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoChristianUActionPerformed(evt);
            }
        });
        jPanel7.add(rdoChristianU, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, 30));

        btngReli.add(rdoHinduU);
        rdoHinduU.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdoHinduU.setForeground(new java.awt.Color(102, 0, 0));
        rdoHinduU.setText("Hindu");
        rdoHinduU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoHinduUActionPerformed(evt);
            }
        });
        jPanel7.add(rdoHinduU, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 0, 0));
        jLabel19.setText("Religion");
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 80, 20));

        btngReli.add(rdoBuddishU);
        rdoBuddishU.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdoBuddishU.setForeground(new java.awt.Color(102, 0, 0));
        rdoBuddishU.setText("Buddish");
        rdoBuddishU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoBuddishUActionPerformed(evt);
            }
        });
        jPanel7.add(rdoBuddishU, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, 30));

        btngNation.add(rdoMyanmarU);
        rdoMyanmarU.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdoMyanmarU.setForeground(new java.awt.Color(102, 0, 0));
        rdoMyanmarU.setText("Myanmar");
        rdoMyanmarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoMyanmarUActionPerformed(evt);
            }
        });
        jPanel7.add(rdoMyanmarU, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 0));
        jLabel8.setText(":");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 10, 20));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 0, 0));
        jLabel25.setText(":");
        jPanel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 10, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 0, 0));
        jLabel26.setText(":");
        jPanel7.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 10, -1));

        Page1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, 520, 230));

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setBackground(new java.awt.Color(153, 153, 153));
        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(153, 0, 0));
        jLabel28.setText("Contact Info");
        jPanel8.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 40));

        Page1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 120, 30));

        jPanel4.setBackground(new java.awt.Color(153, 0, 0));
        jPanel4.setMinimumSize(new java.awt.Dimension(1100, 65));
        jPanel4.setPreferredSize(new java.awt.Dimension(1200, 65));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labHomeU1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hupdate.png"))); // NOI18N
        labHomeU1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labHomeU1MouseClicked(evt);
            }
        });
        jPanel5.add(labHomeU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 0, -1, -1));

        jLabel6.setBackground(new java.awt.Color(204, 0, 0));
        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Student Updating");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.setVerifyInputWhenFocusTarget(false);
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, -10, 340, 60));

        labBackU1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Back.png"))); // NOI18N
        labBackU1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labBackU1MouseClicked(evt);
            }
        });
        jPanel5.add(labBackU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 50));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1080, 50));

        Page1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 70));

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 0, 0));
        jLabel14.setText("Phone No");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 140, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 0, 0));
        jLabel16.setText("Telegram No");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 150, -1));

        txtstdPhnoU.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtstdPhnoU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstdPhnoUActionPerformed(evt);
            }
        });
        jPanel6.add(txtstdPhnoU, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 210, -1));

        txtstdEmailU.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtstdEmailU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstdEmailUActionPerformed(evt);
            }
        });
        jPanel6.add(txtstdEmailU, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 210, -1));

        txtstdTeleU.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtstdTeleU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstdTeleUActionPerformed(evt);
            }
        });
        jPanel6.add(txtstdTeleU, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 210, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 0, 0));
        jLabel22.setText(":");
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 20, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 0, 0));
        jLabel23.setText(":");
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 20, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 0, 0));
        jLabel24.setText(":");
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 20, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(102, 0, 0));
        jLabel30.setText("Email No");
        jPanel6.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 140, -1));

        Page1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 480, 230));

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(153, 153, 153));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 0, 0));
        jLabel11.setText("Basic Info");
        jPanel9.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 40));

        Page1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 100, 40));

        btnUpdate1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnUpdate1.setForeground(new java.awt.Color(102, 0, 0));
        btnUpdate1.setText("Update");
        btnUpdate1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdate1MouseClicked(evt);
            }
        });
        btnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate1ActionPerformed(evt);
            }
        });
        Page1.add(btnUpdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 640, 100, -1));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 0));
        jLabel7.setText("Date of birth");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 150, -1));

        txtstdIdU.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtstdIdU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstdIdUActionPerformed(evt);
            }
        });
        jPanel3.add(txtstdIdU, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 210, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 0));
        jLabel10.setText("Student's ID  ");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 140, -1));

        txtstdNRCU.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtstdNRCU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstdNRCUActionPerformed(evt);
            }
        });
        jPanel3.add(txtstdNRCU, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 210, -1));

        txtstdNameU.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtstdNameU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstdNameUActionPerformed(evt);
            }
        });
        jPanel3.add(txtstdNameU, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 210, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 0));
        jLabel9.setText("Student's Name  ");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 140, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 0, 0));
        jLabel12.setText(":");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 20, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 0, 0));
        jLabel13.setText(":");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 20, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 0, 0));
        jLabel20.setText(":");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 20, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 0, 0));
        jLabel21.setText(":");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 20, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 0, 0));
        jLabel27.setText("NRC No");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 130, -1));

        lblupdateimg.setForeground(new java.awt.Color(255, 51, 51));
        lblupdateimg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(lblupdateimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 250, 190));

        txtstd_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstd_idActionPerformed(evt);
            }
        });
        jPanel3.add(txtstd_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 70, 20));
        jPanel3.add(txtimgpath, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 229, 70, 20));

        btnbrowse.setText("Add Photo");
        btnbrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbrowseActionPerformed(evt);
            }
        });
        jPanel3.add(btnbrowse, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 110, 30));
        jPanel3.add(txtdateu, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 210, -1));

        Page1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 1030, 260));

        btnNext1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnNext1.setForeground(new java.awt.Color(102, 0, 0));
        btnNext1.setText("Next");
        btnNext1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNext1MouseClicked(evt);
            }
        });
        btnNext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext1ActionPerformed(evt);
            }
        });
        Page1.add(btnNext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 640, 100, -1));

        btnClear1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnClear1.setForeground(new java.awt.Color(102, 0, 0));
        btnClear1.setText("Clear");
        btnClear1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClear1MouseClicked(evt);
            }
        });
        btnClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear1ActionPerformed(evt);
            }
        });
        Page1.add(btnClear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 640, 100, -1));

        getContentPane().add(Page1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 690));
        Page2.setVisible(false);
        Page3.setVisible(false);

        Page2.setBackground(new java.awt.Color(204, 204, 204));
        Page2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        Page2.setMinimumSize(new java.awt.Dimension(1100, 690));
        Page2.setPreferredSize(new java.awt.Dimension(1100, 690));
        Page2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(204, 204, 204));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(102, 0, 0));
        jLabel40.setText("Enter Relationship's data");
        jPanel13.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 20));

        Page2.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 210, 30));

        jPanel14.setBackground(new java.awt.Color(204, 204, 204));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPhnoRsU2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPhnoRsU2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhnoRsU2ActionPerformed(evt);
            }
        });
        jPanel14.add(txtPhnoRsU2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 230, -1));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(102, 0, 0));
        jLabel41.setText(":");
        jPanel14.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 20, -1));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(102, 0, 0));
        jLabel42.setText("Phone number");
        jPanel14.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 140, -1));

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(102, 0, 0));
        jLabel43.setText(":");
        jPanel14.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 20, -1));

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(102, 0, 0));
        jLabel44.setText("Relationship_Type");
        jPanel14.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 150, -1));

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(102, 0, 0));
        jLabel45.setText(":");
        jPanel14.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 20, -1));

        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(102, 0, 0));
        jLabel46.setText("Occuupation");
        jPanel14.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 130, -1));

        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(102, 0, 0));
        jLabel47.setText(":");
        jPanel14.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 20, -1));

        cboRSTypeU2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Father ", "Mother", "Wife", "Husband" }));
        jPanel14.add(cboRSTypeU2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 230, 30));

        jLabel51.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(102, 0, 0));
        jLabel51.setText("Name  ");
        jPanel14.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, -1));

        txtAreaOccuU2.setColumns(20);
        txtAreaOccuU2.setRows(5);
        jScrollPane3.setViewportView(txtAreaOccuU2);

        jPanel14.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 230, 90));

        txtRSNameU3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtRSNameU3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRSNameU3ActionPerformed(evt);
            }
        });
        jPanel14.add(txtRSNameU3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 230, -1));

        txtupstdid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtupstdidActionPerformed(evt);
            }
        });
        jPanel14.add(txtupstdid, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 60, 20));

        Page2.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 420, 400));

        jPanel15.setBackground(new java.awt.Color(153, 0, 0));
        jPanel15.setMinimumSize(new java.awt.Dimension(1100, 65));
        jPanel15.setPreferredSize(new java.awt.Dimension(1200, 65));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setBackground(new java.awt.Color(204, 204, 204));
        jPanel16.setForeground(new java.awt.Color(102, 0, 0));
        jPanel16.setAutoscrolls(true);
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel49.setBackground(new java.awt.Color(204, 0, 0));
        jLabel49.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(204, 0, 0));
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("Student Updating");
        jLabel49.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel49.setVerifyInputWhenFocusTarget(false);
        jPanel16.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, -10, 340, 60));

        labBackA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Back.png"))); // NOI18N
        labBackA2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labBackA2MouseClicked(evt);
            }
        });
        jPanel16.add(labBackA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hupdate.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel16.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 0, 50, 50));

        jPanel15.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1080, 50));

        Page2.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 70));

        jTableRsA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Rid", "Name", "Ph_No", "Occupation", "RS_Type"
            }
        ));
        jscrolRsA.setViewportView(jTableRsA);

        Page2.add(jscrolRsA, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 610, 400));

        btnNext2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnNext2.setForeground(new java.awt.Color(102, 0, 0));
        btnNext2.setText("Next");
        btnNext2.setAutoscrolls(true);
        btnNext2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNext2MouseClicked(evt);
            }
        });
        btnNext2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext2ActionPerformed(evt);
            }
        });
        Page2.add(btnNext2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 640, 100, -1));

        jPanel18.setBackground(new java.awt.Color(204, 204, 204));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel50.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(102, 0, 0));
        jLabel50.setText("Enter Address");
        jPanel18.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 110, 60));

        Page2.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 120, 40));

        jPanel17.setBackground(new java.awt.Color(204, 204, 204));
        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel52.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(102, 0, 0));
        jLabel52.setText("Region");
        jPanel17.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 70, -1));

        jLabel53.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(102, 0, 0));
        jLabel53.setText(":");
        jPanel17.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 10, -1));

        jLabel54.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(102, 0, 0));
        jLabel54.setText("City");
        jPanel17.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 30, -1));

        jLabel55.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(102, 0, 0));
        jLabel55.setText(":");
        jPanel17.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 20, -1));

        jLabel56.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(102, 0, 0));
        jLabel56.setText("Township");
        jPanel17.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 80, -1));

        jLabel57.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(102, 0, 0));
        jLabel57.setText(":");
        jPanel17.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, 20, -1));

        txtTownshipU2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTownshipU2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTownshipU2ActionPerformed(evt);
            }
        });
        jPanel17.add(txtTownshipU2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 30, 230, -1));

        txtRegionU2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtRegionU2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegionU2ActionPerformed(evt);
            }
        });
        jPanel17.add(txtRegionU2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 230, -1));

        txtCityU2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCityU2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityU2ActionPerformed(evt);
            }
        });
        jPanel17.add(txtCityU2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 230, -1));

        Page2.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 1040, 110));

        btnUpdate2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnUpdate2.setForeground(new java.awt.Color(102, 0, 0));
        btnUpdate2.setText("Update");
        btnUpdate2.setAutoscrolls(true);
        btnUpdate2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdate2MouseClicked(evt);
            }
        });
        btnUpdate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate2ActionPerformed(evt);
            }
        });
        Page2.add(btnUpdate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 640, 100, -1));

        btnClear2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnClear2.setForeground(new java.awt.Color(102, 0, 0));
        btnClear2.setText("Clear");
        btnClear2.setAutoscrolls(true);
        btnClear2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClear2MouseClicked(evt);
            }
        });
        btnClear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear2ActionPerformed(evt);
            }
        });
        Page2.add(btnClear2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 640, 100, -1));

        getContentPane().add(Page2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 690));
        Page3.setVisible(false);

        Page3.setBackground(new java.awt.Color(204, 204, 204));
        Page3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        Page3.setMinimumSize(new java.awt.Dimension(1100, 690));
        Page3.setPreferredSize(new java.awt.Dimension(1100, 690));
        Page3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(102, 0, 0));
        jLabel32.setText("Enter Education Background");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 220, 80));

        Page3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 240, 60));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtOrgA3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtOrgA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrgA3ActionPerformed(evt);
            }
        });
        jPanel1.add(txtOrgA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, 230, -1));

        txtDipoNameU3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtDipoNameU3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDipoNameU3ActionPerformed(evt);
            }
        });
        jPanel1.add(txtDipoNameU3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 230, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(102, 0, 0));
        jLabel31.setText(":");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 20, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(102, 0, 0));
        jLabel33.setText("Field Name");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 140, -1));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(102, 0, 0));
        jLabel34.setText(":");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, 20, -1));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(102, 0, 0));
        jLabel35.setText("From-Date");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 110, -1));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(102, 0, 0));
        jLabel36.setText(":");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 20, -1));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(102, 0, 0));
        jLabel37.setText("Orgnization Name");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 150, -1));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(102, 0, 0));
        jLabel38.setText(":");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, 20, -1));

        cboDipoTypeU3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Degree", "Diploma", "Certificate" }));
        cboDipoTypeU3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDipoTypeU3ActionPerformed(evt);
            }
        });
        jPanel1.add(cboDipoTypeU3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 230, 30));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(102, 0, 0));
        jLabel39.setText("Diploma Name ");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 140, -1));

        txtFieldU3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtFieldU3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldU3ActionPerformed(evt);
            }
        });
        jPanel1.add(txtFieldU3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 50, 230, -1));

        jLabel48.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(102, 0, 0));
        jLabel48.setText("Type");
        jPanel1.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 150, -1));

        jLabel58.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(102, 0, 0));
        jLabel58.setText(":");
        jPanel1.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 20, -1));

        jLabel59.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(102, 0, 0));
        jLabel59.setText("To-Date");
        jPanel1.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 110, -1));

        jLabel60.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(102, 0, 0));
        jLabel60.setText(":");
        jPanel1.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 180, 20, -1));

        jTableEDUU3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Diploma_Name", "Field_Name", "Type", "Org_Name", "From_date", "To_date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jscrolEDUU3.setViewportView(jTableEDUU3);

        jPanel1.add(jscrolEDUU3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 990, 200));
        jPanel1.add(DateChFromU3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 230, -1));
        jPanel1.add(DateChToU3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 170, 230, -1));

        Page3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 1050, 480));

        jPanel11.setBackground(new java.awt.Color(153, 0, 0));
        jPanel11.setMinimumSize(new java.awt.Dimension(1100, 65));
        jPanel11.setPreferredSize(new java.awt.Dimension(1200, 65));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(204, 204, 204));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setBackground(new java.awt.Color(204, 0, 0));
        jLabel17.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Student Updating");
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel17.setVerifyInputWhenFocusTarget(false);
        jPanel12.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, -10, 340, 60));

        labBackA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Back.png"))); // NOI18N
        labBackA3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labBackA3MouseClicked(evt);
            }
        });
        jPanel12.add(labBackA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hupdate.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel12.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 0, -1, 50));

        jPanel11.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1080, 50));

        Page3.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 70));

        btnFinish3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnFinish3.setForeground(new java.awt.Color(102, 0, 0));
        btnFinish3.setText("Finish");
        btnFinish3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFinish3MouseClicked(evt);
            }
        });
        btnFinish3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinish3ActionPerformed(evt);
            }
        });
        Page3.add(btnFinish3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 640, 100, -1));

        btnUpdate3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnUpdate3.setForeground(new java.awt.Color(102, 0, 0));
        btnUpdate3.setText("Update");
        btnUpdate3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdate3MouseClicked(evt);
            }
        });
        btnUpdate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate3ActionPerformed(evt);
            }
        });
        Page3.add(btnUpdate3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 640, 100, -1));

        btnClear3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnClear3.setForeground(new java.awt.Color(102, 0, 0));
        btnClear3.setText("Clear");
        btnClear3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClear3MouseClicked(evt);
            }
        });
        btnClear3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear3ActionPerformed(evt);
            }
        });
        Page3.add(btnClear3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 640, 100, -1));

        getContentPane().add(Page3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdoIslumUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoIslumUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoIslumUActionPerformed

    private void rdoMaleUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoMaleUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoMaleUActionPerformed

    private void rdoOtherUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoOtherUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoOtherUActionPerformed

    private void rdoChristianUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoChristianUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoChristianUActionPerformed

    private void rdoHinduUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoHinduUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoHinduUActionPerformed

    private void rdoBuddishUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoBuddishUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoBuddishUActionPerformed

    private void rdoMyanmarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoMyanmarUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoMyanmarUActionPerformed

    private void labBackU1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labBackU1MouseClicked
        new StdFirstPage_View_IT().setVisible(true);
    }//GEN-LAST:event_labBackU1MouseClicked

    private void txtstdPhnoUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstdPhnoUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstdPhnoUActionPerformed

    private void txtstdEmailUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstdEmailUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstdEmailUActionPerformed

    private void txtstdTeleUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstdTeleUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstdTeleUActionPerformed

    private void txtstdIdUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstdIdUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstdIdUActionPerformed

    private void txtstdNRCUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstdNRCUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstdNRCUActionPerformed

    private void txtstdNameUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstdNameUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstdNameUActionPerformed

    private void btnUpdate1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdate1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdate1MouseClicked

    private void btnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate1ActionPerformed
        StdFirstPage_View_IT fp = new  StdFirstPage_View_IT();              
//        i =(int)fp.jTableItStd.getValueAt(sRow, 0);
                            int ids=Integer.parseInt(txtstd_id.getText());
			    String name=txtstdNameU.getText().trim();
                            String std_no=txtstdIdU.getText();
			    Date d= new Date(txtdateu.getDate().getTime());
		              String gender = null;
                          if (rdoMaleU.isSelected()) {
                           gender = "Male";
                              } else if (rdoFemaleU.isSelected()) {
                              gender = "Female";
                               }
                       

                          String religion = null;
                          if (rdoBuddishU.isSelected()) {
                          religion = "Buddish";
                          } else if (rdoChristianU.isSelected()) {
                          religion = "Christian";
                          } else if (rdoHinduU.isSelected()) {
                          religion = "Hindu";
                          }else if(rdoIslumU.isSelected())
			    religion="Islum";
		            String pno=txtstdPhnoU.getText();

			    String email=txtstdEmailU.getText();
                            String tele_no=txtstdTeleU.getText();
                           // String nr=combNRC.getSelectedItem().toString();
                            
			     String nation=null;
			    if(rdoMyanmarU.isSelected()){
			    nation="Myanmar";
                            }else if(rdoOtherU.isSelected())
			    nation="Other";
                            //String photo=jLabelPhotoA.getText();
                            String nrc=txtstdNRCU.getText();
                            String imgpath=txtimgpath.getText();
                    int choice=JOptionPane.showConfirmDialog(null, "Do you really want to save your data","Confirm Message",JOptionPane.INFORMATION_MESSAGE);
                    if(choice==JOptionPane.YES_OPTION){
               Student std;
              std=new Student(ids,std_no,name,d,email,pno,gender,religion,nation,tele_no,nrc,imgpath);
                    StudentDAO stdao=new StudentDAO();
                    System.out.println(std.getStd_id());
                   stdao.updateDataStd(std,imgpath);

                    }
                              
         
       

                                
    }//GEN-LAST:event_btnUpdate1ActionPerformed

    private void btnNext1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNext1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNext1MouseClicked

    private void btnNext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext1ActionPerformed
        Page1.setVisible(false);
        Page2.setVisible(true);
        Page3.setVisible(false);
        txtupstdid.setVisible(false);
//        txtupstdid.setVisible(false);
        int idst=Integer.parseInt(txtstd_id.getText());
        RelationshipDAO rdao=new RelationshipDAO();
        Relationship rs=rdao.returnAllDataToTextfieldRS(idst);
        txtupstdid.setText(String.valueOf(rs.getStd_id()));
        txtRSNameU3.setText(rs.getName());
        txtPhnoRsU2.setText(rs.getPhno());
        cboRSTypeU2.setSelectedItem(rs.getRs_type());
        txtAreaOccuU2.setText(rs.getOccupation());
          
            RelationshipDAO rsdao=new RelationshipDAO();
            ArrayList list=rsdao.loadupdatedataRS(idst);
            loadAllDataintoTableRS(list);
          
            AddressDAO ado=new AddressDAO();
//            Address add=new Address();
             Address add=ado.returnAllDataToTextfieldAdd(idst);
//             txtaid.setText(String.valueOf(add.getAid()));
             txtRegionU2.setText(add.getRegion());
             txtCityU2.setText(add.getCity());
             txtTownshipU2.setText(add.getTown());
             

    }//GEN-LAST:event_btnNext1ActionPerformed

    private void btnClear1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClear1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClear1MouseClicked

    private void btnClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear1ActionPerformed
        txtstdNameU.setText("");
        txtstdIdU.setText("");
        txtdateu.setDate(null);
        txtstdNRCU.setText("");
        txtstdEmailU.setText("");
        txtstdTeleU.setText("");
        txtstdPhnoU.setText("");

    }//GEN-LAST:event_btnClear1ActionPerformed

    private void labBackA3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labBackA3MouseClicked
        Page1.setVisible(false);
        Page2.setVisible(true);
        Page3.setVisible(false);
    }//GEN-LAST:event_labBackA3MouseClicked

    private void txtOrgA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrgA3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrgA3ActionPerformed

    private void txtDipoNameU3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDipoNameU3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDipoNameU3ActionPerformed

    private void btnUpdate3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdate3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdate3MouseClicked

    private void btnUpdate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate3ActionPerformed
       int idst=Integer.parseInt(txtstd_id.getText());
       QualificationDAO qdao=new QualificationDAO();
      
     int index = jTableEDUU3.getSelectedRow();
        if(index<0){
               JOptionPane.showMessageDialog(null, "Please select any record from table for update");
            }else
            {  
                DefaultTableModel model = (DefaultTableModel)jTableEDUU3.getModel();
//             int rowId = Integer.parseInt(jTableEDUU3.getValueAt(index, 0).toString());
             String dip= txtDipoNameU3.getText();
             String tf=txtFieldU3.getText();
              String org=txtOrgA3.getText();
             String cbodip=cboDipoTypeU3.getSelectedItem().toString();
             Date fd=new Date(DateChFromU3.getDate().getTime());
             Date td=new Date(DateChToU3.getDate().getTime());
             Qualification qua=new Qualification(0,idst,dip,tf,org,cbodip,fd,td);
             qdao.updateDataQua(qua);
             ArrayList list=qdao.loadUpdatedataQua(idst);
            loadAllDataintoTableQua(list);
             
            }
       
    }//GEN-LAST:event_btnUpdate3ActionPerformed

    private void btnFinish3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinish3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFinish3MouseClicked

    private void btnFinish3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinish3ActionPerformed
//        int choice=JOptionPane.showConfirmDialog(null,"Are you really sure to finish your add data!!!","Confirm Message",JOptionPane.INFORMATION_MESSAGE);
//        if(choice==JOptionPane.YES_OPTION){
            new StdFirstPage_View_IT().setVisible(true);
    
//        }
    }//GEN-LAST:event_btnFinish3ActionPerformed

    private void btnClear3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClear3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClear3MouseClicked

    private void btnClear3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClear3ActionPerformed

    private void txtPhnoRsU2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhnoRsU2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhnoRsU2ActionPerformed

    private void txtTownshipU2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTownshipU2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTownshipU2ActionPerformed

    private void btnUpdate2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdate2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdate2MouseClicked

    private void btnUpdate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate2ActionPerformed
        int idst=Integer.parseInt(txtupstdid.getText());
        RelationshipDAO rdao=new RelationshipDAO();
        Relationship rs=rdao.returnAllDataToTextfieldRS(idst); 
        int index = jTableRsA.getSelectedRow();
        if(index<0){
               JOptionPane.showMessageDialog(null, "Please select any record from table for update");
            }else
            {  
                DefaultTableModel model = (DefaultTableModel)jTableRsA.getModel();
                    int rowId = Integer.parseInt(jTableRsA.getValueAt(index, 0).toString());
        String upname=txtRSNameU3.getText();
        String phnoup=txtPhnoRsU2.getText();
        String rst=cboRSTypeU2.getSelectedItem().toString();
        String occ=txtAreaOccuU2.getText();
        rs=new Relationship(rowId,idst,upname,phnoup,occ,rst);
        rdao.updateDataRS(rs);  
        ArrayList list=rdao.loadupdatedataRS(idst);
        loadAllDataintoTableRS(list);
//        int ade=Integer.parseInt(txtaid.getText());
        String reg=txtRegionU2.getText();
        String city=txtCityU2.getText();
        String town=txtTownshipU2.getText();
        Address add=new Address(0,idst,reg,city,town);
        AddressDAO ado=new AddressDAO();
        ado.updateDataAdd(add);
            }
    }//GEN-LAST:event_btnUpdate2ActionPerformed

    private void btnClear2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClear2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClear2MouseClicked

    private void btnClear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear2ActionPerformed
       txtRSNameU3.setText("");
       txtPhnoRsU2.setText("");
       cboRSTypeU2.setSelectedItem(null);
       txtAreaOccuU2.setText("");
    }//GEN-LAST:event_btnClear2ActionPerformed

    private void labBackA2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labBackA2MouseClicked
        Page1.setVisible(true);
        Page2.setVisible(false);
        Page3.setVisible(false);
    }//GEN-LAST:event_labBackA2MouseClicked

    private void btnNext2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNext2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNext2MouseClicked

    private void btnNext2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext2ActionPerformed
        Page1.setVisible(false);
        Page2.setVisible(false);
        Page3.setVisible(true);
        
         int idst=Integer.parseInt(txtupstdid.getText());
             QualificationDAO qdao=new QualificationDAO();
             Qualification qua=qdao.returnAllDataToTextfieldQua(idst);
             txtDipoNameU3.setText(qua.getDip_name());
             cboDipoTypeU3.setSelectedItem(qua.getType());
             DateChFromU3.setDate(qua.getFrom_date());
             txtFieldU3.setText(qua.getField_name());
             txtOrgA3.setText(qua.getOrg_name());
             DateChToU3.setDate(qua.getTo_date());
             
            ArrayList list=qdao.loadUpdatedataQua(idst);
            loadAllDataintoTableQua(list);
            
    }//GEN-LAST:event_btnNext2ActionPerformed

    private void txtFieldU3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldU3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldU3ActionPerformed

    private void txtRSNameU3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRSNameU3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRSNameU3ActionPerformed

    private void txtRegionU2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegionU2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegionU2ActionPerformed

    private void txtCityU2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityU2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityU2ActionPerformed

    private void txtupstdidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtupstdidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtupstdidActionPerformed

    private void txtstd_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstd_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstd_idActionPerformed

    private void cboDipoTypeU3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDipoTypeU3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDipoTypeU3ActionPerformed

    private void btnbrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbrowseActionPerformed
         JFileChooser fileChooser = new JFileChooser();
                int option = fileChooser.showOpenDialog(null);
                if (option == JFileChooser.APPROVE_OPTION) {
                    File selectedFile = fileChooser.getSelectedFile();
                    txtimgpath.setText(selectedFile.getAbsolutePath());
                    displaySelectedImage(selectedFile);
                }
    }//GEN-LAST:event_btnbrowseActionPerformed

    private void labHomeU1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labHomeU1MouseClicked
        dispose();
        AdminPanel ad = new AdminPanel();
       ad.setVisible(true);
       ad.loginPane.setVisible(false);
        ad.logoutpane.setVisible(false);
    }//GEN-LAST:event_labHomeU1MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
      dispose();
        AdminPanel ad = new AdminPanel();
       ad.setVisible(true);
       ad.loginPane.setVisible(false);
       ad.logoutpane.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
     dispose();
        AdminPanel ad = new AdminPanel();
     ad.setVisible(true);
     ad.loginPane.setVisible(false);
     ad.logoutpane.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ITstdUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ITstdUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ITstdUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ITstdUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ITstdUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateChFromU3;
    private com.toedter.calendar.JDateChooser DateChToU3;
    private javax.swing.JPanel Page1;
    private javax.swing.JPanel Page2;
    private javax.swing.JPanel Page3;
    private javax.swing.JButton btnClear1;
    private javax.swing.JButton btnClear2;
    private javax.swing.JButton btnClear3;
    private javax.swing.JButton btnFinish3;
    private javax.swing.JButton btnNext1;
    private javax.swing.JButton btnNext2;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JButton btnUpdate2;
    private javax.swing.JButton btnUpdate3;
    private javax.swing.JButton btnbrowse;
    private javax.swing.ButtonGroup btngGender;
    private javax.swing.ButtonGroup btngNation;
    private javax.swing.ButtonGroup btngReli;
    private javax.swing.JComboBox<String> cboDipoTypeU3;
    private javax.swing.JComboBox<String> cboRSTypeU2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableEDUU3;
    private javax.swing.JTable jTableRsA;
    private javax.swing.JScrollPane jscrolEDUU3;
    private javax.swing.JScrollPane jscrolRsA;
    private javax.swing.JLabel labBackA2;
    private javax.swing.JLabel labBackA3;
    private javax.swing.JLabel labBackU1;
    private javax.swing.JLabel labHomeU1;
    public javax.swing.JLabel lblupdateimg;
    public javax.swing.JRadioButton rdoBuddishU;
    public javax.swing.JRadioButton rdoChristianU;
    public javax.swing.JRadioButton rdoFemaleU;
    public javax.swing.JRadioButton rdoHinduU;
    public javax.swing.JRadioButton rdoIslumU;
    public javax.swing.JRadioButton rdoMaleU;
    public javax.swing.JRadioButton rdoMyanmarU;
    public javax.swing.JRadioButton rdoOtherU;
    private javax.swing.JTextArea txtAreaOccuU2;
    private javax.swing.JTextField txtCityU2;
    private javax.swing.JTextField txtDipoNameU3;
    private javax.swing.JTextField txtFieldU3;
    private javax.swing.JTextField txtOrgA3;
    private javax.swing.JTextField txtPhnoRsU2;
    private javax.swing.JTextField txtRSNameU3;
    private javax.swing.JTextField txtRegionU2;
    private javax.swing.JTextField txtTownshipU2;
    public com.toedter.calendar.JDateChooser txtdateu;
    public javax.swing.JTextField txtimgpath;
    public javax.swing.JTextField txtstdEmailU;
    public javax.swing.JTextField txtstdIdU;
    public javax.swing.JTextField txtstdNRCU;
    public javax.swing.JTextField txtstdNameU;
    public javax.swing.JTextField txtstdPhnoU;
    public javax.swing.JTextField txtstdTeleU;
    public javax.swing.JTextField txtstd_id;
    private javax.swing.JTextField txtupstdid;
    // End of variables declaration//GEN-END:variables

  
     public int getStudentID() throws SQLException{
            int id=0;
            String maxId = "SELECT MAX(std_id) FROM student";
            
            PreparedStatement statement = con.prepareStatement(maxId);
            ResultSet rs = statement.executeQuery();
            
            
            while (rs.next()) {
                id = rs.getInt(1);
                
            }
             return id;
        }
     
      public void loadAllDataintoTableRS(ArrayList<Relationship>list){
        
        DefaultTableModel dtm=(DefaultTableModel) jTableRsA.getModel(); 
        dtm.setRowCount(0);
        
        for(Relationship rs :list){
            Vector v=new Vector();
            v.add(rs.getRid());
            v.add(rs.getName());
            v.add(rs.getPhno());
            v.add(rs.getOccupation());
            v.add(rs.getRs_type());

            dtm.addRow(v);
            
        } 
      }
      
            public void loadAllDataintoTableQua(ArrayList<Qualification>list){
        
        DefaultTableModel dtm=(DefaultTableModel) jTableEDUU3.getModel(); 
        dtm.setRowCount(0);
        
        for(Qualification qua :list){
            Vector v=new Vector();
           v.add(qua.getDip_name());
           v.add(qua.getField_name());
           v.add(qua.getType());
            v.add(qua.getOrg_name());
           v.add(qua.getFrom_date());
           v.add(qua.getTo_date());

            dtm.addRow(v);
            
        } 
      }
//        public void loadtableRs(){
//            
//            RelationshipDAO rsdao=new RelationshipDAO();
//            ArrayList list=rsdao.loadupdatedataRS(sidd);
//            loadAllDataintoTableRS(list);
//        }
            
             public void displaySelectedImage(File selectedFile) {
        try {
            Image image = ImageIO.read(selectedFile);
            if (image != null) {
                // Resize the image to fit the JLabel
                Image resizedImage = image.getScaledInstance(lblupdateimg.getWidth(),
                        lblupdateimg.getHeight(), Image.SCALE_SMOOTH);
              lblupdateimg.setIcon(new ImageIcon(resizedImage));
            } else {
                lblupdateimg.setIcon(null);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

}
