/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package ITStudent;

import AdminLogin.AdminPanel;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.RowFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author User
 */
public class ITstdadd extends javax.swing.JFrame {
    private Connection con;
    /** Creates new form ITstdadd */
    public ITstdadd() {
        initComponents();
         Image ic=new ImageIcon(this.getClass().getResource("/jpro.jpg")).getImage();
        this.setIconImage(ic);
            try{
             con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Jpro_InfoHub","root","root");
        }
        catch(SQLException e){
         e.printStackTrace();
        }
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngGender = new javax.swing.ButtonGroup();
        btngReli = new javax.swing.ButtonGroup();
        btngNation = new javax.swing.ButtonGroup();
        Page2 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        txtPhnoRsA2 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        cboRSTypeA2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaOccuA2 = new javax.swing.JTextArea();
        txtRSNameA2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        labBackA2 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jscrolRsA = new javax.swing.JScrollPane();
        jTableRsA = new javax.swing.JTable();
        btnNext2 = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        txtTownshipA2 = new javax.swing.JTextField();
        txtRegionA2 = new javax.swing.JTextField();
        txtCityA2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        btnAdd2 = new javax.swing.JButton();
        btnClear2 = new javax.swing.JButton();
        Page1 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        rdoFemaleA = new javax.swing.JRadioButton();
        rdoIslumA = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        rdoMaleA = new javax.swing.JRadioButton();
        rdoOtherA = new javax.swing.JRadioButton();
        rdoChristianA = new javax.swing.JRadioButton();
        rdoHinduA = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        rdoBuddishA = new javax.swing.JRadioButton();
        rdoMyanmarA = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        labHomeA1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labBackA1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtstdPhnoA = new javax.swing.JTextField();
        txtstdEmailA = new javax.swing.JTextField();
        txtstdTeleA = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtstdIdA = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtstdNRCA = new javax.swing.JTextField();
        txtstdNameA = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jphoto = new javax.swing.JLabel();
        jfilechose = new javax.swing.JButton();
        txtimage = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        DateChA = new com.toedter.calendar.JDateChooser();
        button1 = new java.awt.Button();
        btnNext1 = new javax.swing.JButton();
        btnClear1 = new javax.swing.JButton();
        Page3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtOrgA3 = new javax.swing.JTextField();
        txtDipoNameA3 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        cboDipoTypeA3 = new javax.swing.JComboBox<>();
        jLabel39 = new javax.swing.JLabel();
        txtFieldA3 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jscrolEDUA3 = new javax.swing.JScrollPane();
        jTableEDUA3 = new javax.swing.JTable();
        DateChFromA3 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        labBackA3 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        btnFinish3 = new javax.swing.JButton();
        btnAdd3 = new javax.swing.JButton();
        btnClear3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JPRO InfoHub Course Management System");
        setMinimumSize(new java.awt.Dimension(1100, 690));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Page2.setBackground(new java.awt.Color(204, 204, 204));
        Page2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        Page2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(204, 204, 204));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(102, 0, 0));
        jLabel40.setText("Enter Relationship's data");
        jPanel13.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 20));

        Page2.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 210, 30));

        jPanel14.setBackground(new java.awt.Color(204, 204, 204));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPhnoRsA2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPhnoRsA2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPhnoRsA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhnoRsA2ActionPerformed(evt);
            }
        });
        jPanel14.add(txtPhnoRsA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 230, -1));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(102, 0, 0));
        jLabel41.setText(":");
        jPanel14.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 20, -1));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(102, 0, 0));
        jLabel42.setText("Phone number");
        jPanel14.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 140, -1));

        jLabel43.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(102, 0, 0));
        jLabel43.setText(":");
        jPanel14.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 20, -1));

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(102, 0, 0));
        jLabel44.setText("Relationship_Type");
        jPanel14.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 150, -1));

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(102, 0, 0));
        jLabel45.setText(":");
        jPanel14.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 20, -1));

        jLabel46.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(102, 0, 0));
        jLabel46.setText("Occuupation");
        jPanel14.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 130, -1));

        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(102, 0, 0));
        jLabel47.setText(":");
        jPanel14.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 20, -1));

        cboRSTypeA2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Father ", "Mother", "Wife", "Husband" }));
        jPanel14.add(cboRSTypeA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 230, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("*");
        jPanel14.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 20, 20));

        jLabel51.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(102, 0, 0));
        jLabel51.setText("Name  ");
        jPanel14.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, -1));

        txtAreaOccuA2.setColumns(20);
        txtAreaOccuA2.setRows(5);
        jScrollPane3.setViewportView(txtAreaOccuA2);

        jPanel14.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 230, 90));

        txtRSNameA2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtRSNameA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRSNameA2ActionPerformed(evt);
            }
        });
        jPanel14.add(txtRSNameA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 230, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("*");
        jPanel14.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 20, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("*");
        jPanel14.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 20, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setText("*");
        jPanel14.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 20, 20));

        Page2.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 420, 400));

        jPanel15.setBackground(new java.awt.Color(153, 0, 0));
        jPanel15.setMinimumSize(new java.awt.Dimension(1100, 65));
        jPanel15.setPreferredSize(new java.awt.Dimension(1200, 65));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setBackground(new java.awt.Color(204, 204, 204));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel49.setBackground(new java.awt.Color(204, 0, 0));
        jLabel49.setFont(new java.awt.Font("Agency FB", 1, 45)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(204, 0, 0));
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("Student Adding");
        jLabel49.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel49.setVerifyInputWhenFocusTarget(false);
        jPanel16.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, -10, 340, 60));

        labBackA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Back.png"))); // NOI18N
        labBackA2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labBackA2MouseClicked(evt);
            }
        });
        jPanel16.add(labBackA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jLabel73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hupdate.png"))); // NOI18N
        jLabel73.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel73MouseClicked(evt);
            }
        });
        jPanel16.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 0, -1, 50));

        jPanel15.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1080, 50));

        Page2.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 70));

        jTableRsA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Ph_NO", "Occupation", "Rs_Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jscrolRsA.setViewportView(jTableRsA);

        Page2.add(jscrolRsA, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 610, 400));

        btnNext2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnNext2.setForeground(new java.awt.Color(102, 0, 0));
        btnNext2.setText("Next");
        btnNext2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNext2MouseClicked(evt);
            }
        });
        btnNext2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext2ActionPerformed(evt);
            }
        });
        Page2.add(btnNext2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 640, 100, -1));

        jPanel18.setBackground(new java.awt.Color(204, 204, 204));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel50.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(102, 0, 0));
        jLabel50.setText("Enter Address");
        jPanel18.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 110, 60));

        Page2.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 120, 40));

        jPanel17.setBackground(new java.awt.Color(204, 204, 204));
        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        jPanel17.setForeground(new java.awt.Color(102, 0, 0));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel52.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(102, 0, 0));
        jLabel52.setText("Region");
        jPanel17.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 70, -1));

        jLabel53.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(102, 0, 0));
        jLabel53.setText(":");
        jPanel17.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 10, -1));

        jLabel54.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(102, 0, 0));
        jLabel54.setText("City");
        jPanel17.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 30, -1));

        jLabel55.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(102, 0, 0));
        jLabel55.setText(":");
        jPanel17.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 20, -1));

        jLabel56.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(102, 0, 0));
        jLabel56.setText("Township");
        jPanel17.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 80, -1));

        jLabel57.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(102, 0, 0));
        jLabel57.setText(":");
        jPanel17.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, 20, -1));

        txtTownshipA2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTownshipA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTownshipA2ActionPerformed(evt);
            }
        });
        jPanel17.add(txtTownshipA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, 230, -1));

        txtRegionA2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtRegionA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegionA2ActionPerformed(evt);
            }
        });
        jPanel17.add(txtRegionA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 230, -1));

        txtCityA2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCityA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityA2ActionPerformed(evt);
            }
        });
        jPanel17.add(txtCityA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 230, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("*");
        jPanel17.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 20, 20));

        jLabel62.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(255, 0, 51));
        jLabel62.setText("*");
        jPanel17.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 20, 20));

        jLabel63.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 0, 51));
        jLabel63.setText("*");
        jPanel17.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 20, 20));

        Page2.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 1040, 110));

        btnAdd2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnAdd2.setForeground(new java.awt.Color(102, 0, 0));
        btnAdd2.setText("Add");
        btnAdd2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdd2MouseClicked(evt);
            }
        });
        btnAdd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd2ActionPerformed(evt);
            }
        });
        Page2.add(btnAdd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 640, 100, -1));

        btnClear2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnClear2.setForeground(new java.awt.Color(102, 0, 0));
        btnClear2.setText("Clear");
        btnClear2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClear2MouseClicked(evt);
            }
        });
        btnClear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear2ActionPerformed(evt);
            }
        });
        Page2.add(btnClear2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 640, 100, -1));

        getContentPane().add(Page2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 690));

        Page1.setBackground(new java.awt.Color(204, 204, 204));
        Page1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        Page1.setMinimumSize(new java.awt.Dimension(1100, 690));
        Page1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel20.setBackground(new java.awt.Color(204, 204, 204));
        jPanel20.setForeground(new java.awt.Color(204, 204, 204));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setBackground(new java.awt.Color(153, 153, 153));
        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(153, 0, 0));
        jLabel29.setText("General Info");
        jPanel20.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 40));

        Page1.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 110, 60));

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 0, 0));
        jLabel15.setText("Nationality");
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 90, 20));

        btngGender.add(rdoFemaleA);
        rdoFemaleA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdoFemaleA.setForeground(new java.awt.Color(102, 0, 0));
        rdoFemaleA.setText("Female");
        rdoFemaleA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoFemaleAActionPerformed(evt);
            }
        });
        jPanel7.add(rdoFemaleA, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, 30));

        btngReli.add(rdoIslumA);
        rdoIslumA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdoIslumA.setForeground(new java.awt.Color(102, 0, 0));
        rdoIslumA.setText("Islam");
        rdoIslumA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoIslumAActionPerformed(evt);
            }
        });
        jPanel7.add(rdoIslumA, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, -1, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 0, 0));
        jLabel18.setText("Gender");
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 80, 20));

        btngGender.add(rdoMaleA);
        rdoMaleA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdoMaleA.setForeground(new java.awt.Color(102, 0, 0));
        rdoMaleA.setText("Male");
        rdoMaleA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoMaleAActionPerformed(evt);
            }
        });
        jPanel7.add(rdoMaleA, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, 30));

        btngNation.add(rdoOtherA);
        rdoOtherA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdoOtherA.setForeground(new java.awt.Color(102, 0, 0));
        rdoOtherA.setText("Other");
        rdoOtherA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoOtherAActionPerformed(evt);
            }
        });
        jPanel7.add(rdoOtherA, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, 30));

        btngReli.add(rdoChristianA);
        rdoChristianA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdoChristianA.setForeground(new java.awt.Color(102, 0, 0));
        rdoChristianA.setText("Christian");
        rdoChristianA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoChristianAActionPerformed(evt);
            }
        });
        jPanel7.add(rdoChristianA, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, 30));

        btngReli.add(rdoHinduA);
        rdoHinduA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdoHinduA.setForeground(new java.awt.Color(102, 0, 0));
        rdoHinduA.setText("Hindu");
        rdoHinduA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoHinduAActionPerformed(evt);
            }
        });
        jPanel7.add(rdoHinduA, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 0, 0));
        jLabel19.setText("Religion");
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 80, 20));

        btngReli.add(rdoBuddishA);
        rdoBuddishA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdoBuddishA.setForeground(new java.awt.Color(102, 0, 0));
        rdoBuddishA.setText("Buddish");
        rdoBuddishA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoBuddishAActionPerformed(evt);
            }
        });
        jPanel7.add(rdoBuddishA, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, 30));

        btngNation.add(rdoMyanmarA);
        rdoMyanmarA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdoMyanmarA.setForeground(new java.awt.Color(102, 0, 0));
        rdoMyanmarA.setText("Myanmar");
        rdoMyanmarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoMyanmarAActionPerformed(evt);
            }
        });
        jPanel7.add(rdoMyanmarA, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 0));
        jLabel8.setText(":");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 10, 20));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 0, 0));
        jLabel25.setText(":");
        jPanel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 10, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 0, 0));
        jLabel26.setText(":");
        jPanel7.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 10, -1));

        Page1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, 520, 230));

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Page1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, 120, -1));

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setBackground(new java.awt.Color(153, 153, 153));
        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(153, 0, 0));
        jLabel28.setText("Contact Info");
        jPanel8.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 40));

        Page1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 120, 30));

        jPanel19.setBackground(new java.awt.Color(204, 204, 204));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Page1.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 120, 30));

        jPanel4.setBackground(new java.awt.Color(153, 0, 0));
        jPanel4.setMinimumSize(new java.awt.Dimension(1100, 65));
        jPanel4.setPreferredSize(new java.awt.Dimension(1200, 65));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labHomeA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hupdate.png"))); // NOI18N
        labHomeA1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labHomeA1MouseClicked(evt);
            }
        });
        jPanel5.add(labHomeA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 0, -1, -1));

        jLabel6.setBackground(new java.awt.Color(204, 0, 0));
        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 45)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Student Adding");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.setVerifyInputWhenFocusTarget(false);
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, -10, 340, 60));

        labBackA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Back.png"))); // NOI18N
        labBackA1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labBackA1MouseClicked(evt);
            }
        });
        jPanel5.add(labBackA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 50));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1080, 50));

        Page1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 70));

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 0, 0));
        jLabel14.setText("Phone No");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 140, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 0, 0));
        jLabel16.setText("Telegram No");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 150, -1));

        txtstdPhnoA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtstdPhnoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstdPhnoAActionPerformed(evt);
            }
        });
        txtstdPhnoA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtstdPhnoAKeyTyped(evt);
            }
        });
        jPanel6.add(txtstdPhnoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 210, -1));

        txtstdEmailA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtstdEmailA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstdEmailAActionPerformed(evt);
            }
        });
        txtstdEmailA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtstdEmailAKeyTyped(evt);
            }
        });
        jPanel6.add(txtstdEmailA, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 210, -1));

        txtstdTeleA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtstdTeleA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstdTeleAActionPerformed(evt);
            }
        });
        txtstdTeleA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtstdTeleAKeyTyped(evt);
            }
        });
        jPanel6.add(txtstdTeleA, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 210, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 0, 0));
        jLabel22.setText(":");
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 20, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 0, 0));
        jLabel23.setText(":");
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 20, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 0, 0));
        jLabel24.setText(":");
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 20, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(102, 0, 0));
        jLabel30.setText("Email No");
        jPanel6.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 140, -1));

        jLabel67.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 0, 51));
        jLabel67.setText("*");
        jPanel6.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 20, 20));

        jLabel68.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 0, 51));
        jLabel68.setText("*");
        jPanel6.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 20, 20));

        jLabel69.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 0, 51));
        jLabel69.setText("*");
        jPanel6.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 20, 20));

        jLabel70.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 0, 51));
        jLabel70.setText("*");
        jPanel6.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 20, 20));

        jLabel71.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 0, 51));
        jLabel71.setText("*");
        jPanel6.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 20, 20));

        Page1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 480, 230));

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(153, 153, 153));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 0, 0));
        jLabel11.setText("Basic Info");
        jPanel9.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 40));

        Page1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 100, 40));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 0));
        jLabel7.setText("Date of birth");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 150, -1));

        txtstdIdA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtstdIdA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstdIdAActionPerformed(evt);
            }
        });
        jPanel3.add(txtstdIdA, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 210, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 0));
        jLabel10.setText("Student's ID  ");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 140, -1));

        txtstdNRCA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtstdNRCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstdNRCAActionPerformed(evt);
            }
        });
        jPanel3.add(txtstdNRCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 210, -1));

        txtstdNameA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtstdNameA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstdNameAActionPerformed(evt);
            }
        });
        jPanel3.add(txtstdNameA, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 210, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 0));
        jLabel9.setText("Student's Name  ");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 140, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 0, 0));
        jLabel12.setText(":");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 20, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 0, 0));
        jLabel13.setText(":");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 20, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 0, 0));
        jLabel20.setText(":");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 20, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 0, 0));
        jLabel21.setText(":");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 20, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 0, 0));
        jLabel27.setText("NRC No");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 130, -1));

        jphoto.setForeground(new java.awt.Color(255, 51, 51));
        jphoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jphoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 250, 190));

        jfilechose.setText("Add Photo");
        jfilechose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfilechoseActionPerformed(evt);
            }
        });
        jPanel3.add(jfilechose, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 120, 30));
        jPanel3.add(txtimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 229, 40, 20));

        jLabel61.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 0, 51));
        jLabel61.setText("*");
        jPanel3.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 20, 20));

        jLabel64.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(255, 0, 51));
        jLabel64.setText("*");
        jPanel3.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 20, 20));

        jLabel65.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(255, 0, 51));
        jLabel65.setText("*");
        jPanel3.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 20, 20));

        jLabel66.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 0, 51));
        jLabel66.setText("*");
        jPanel3.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 20, 20));
        jPanel3.add(DateChA, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 210, -1));

        button1.setLabel("button1");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel3.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, -1, -1));

        Page1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 1030, 260));

        btnNext1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnNext1.setForeground(new java.awt.Color(102, 0, 0));
        btnNext1.setText("Next");
        btnNext1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNext1MouseClicked(evt);
            }
        });
        btnNext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext1ActionPerformed(evt);
            }
        });
        Page1.add(btnNext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 640, 100, -1));

        btnClear1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnClear1.setForeground(new java.awt.Color(102, 0, 0));
        btnClear1.setText("Clear");
        btnClear1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClear1MouseClicked(evt);
            }
        });
        btnClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear1ActionPerformed(evt);
            }
        });
        Page1.add(btnClear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 640, 100, -1));

        getContentPane().add(Page1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 690));
        Page2.setVisible(false);
        Page3.setVisible(false);

        Page3.setBackground(new java.awt.Color(204, 204, 204));
        Page3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        Page3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(102, 0, 0));
        jLabel32.setText("Enter Education Background");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 220, 80));

        Page3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 240, 60));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        jPanel1.setForeground(new java.awt.Color(102, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtOrgA3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtOrgA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrgA3ActionPerformed(evt);
            }
        });
        jPanel1.add(txtOrgA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, 230, -1));

        txtDipoNameA3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtDipoNameA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDipoNameA3ActionPerformed(evt);
            }
        });
        jPanel1.add(txtDipoNameA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 230, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(102, 0, 0));
        jLabel31.setText(":");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 20, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(102, 0, 0));
        jLabel33.setText("Field Name");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 140, -1));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(102, 0, 0));
        jLabel34.setText(":");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, 20, -1));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(102, 0, 0));
        jLabel35.setText("From-Date");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 110, -1));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(102, 0, 0));
        jLabel36.setText(":");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 20, -1));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(102, 0, 0));
        jLabel37.setText("Orgnization Name");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 150, -1));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(102, 0, 0));
        jLabel38.setText(":");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, 20, -1));

        cboDipoTypeA3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cboDipoTypeA3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Degree", "Diploma", "Certificate" }));
        cboDipoTypeA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDipoTypeA3ActionPerformed(evt);
            }
        });
        jPanel1.add(cboDipoTypeA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 230, 30));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(102, 0, 0));
        jLabel39.setText("Diploma Name ");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 140, -1));

        txtFieldA3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtFieldA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldA3ActionPerformed(evt);
            }
        });
        jPanel1.add(txtFieldA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 50, 230, -1));

        jLabel48.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(102, 0, 0));
        jLabel48.setText("Type");
        jPanel1.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 150, -1));

        jLabel58.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(102, 0, 0));
        jLabel58.setText(":");
        jPanel1.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 20, -1));

        jLabel59.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(102, 0, 0));
        jLabel59.setText("To-Date");
        jPanel1.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 110, -1));

        jLabel60.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(102, 0, 0));
        jLabel60.setText(":");
        jPanel1.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 180, 20, -1));

        jTableEDUA3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Diploma_Name", "Field_Name", "Type", "Org_Name", "From_date", "To_date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jscrolEDUA3.setViewportView(jTableEDUA3);

        jPanel1.add(jscrolEDUA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 990, 200));
        jPanel1.add(DateChFromA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 230, -1));
        jPanel1.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 170, 230, -1));

        Page3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 1050, 480));

        jPanel11.setBackground(new java.awt.Color(153, 0, 0));
        jPanel11.setMinimumSize(new java.awt.Dimension(1100, 65));
        jPanel11.setPreferredSize(new java.awt.Dimension(1200, 65));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(204, 204, 204));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setBackground(new java.awt.Color(204, 0, 0));
        jLabel17.setFont(new java.awt.Font("Agency FB", 1, 45)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Student Adding");
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel17.setVerifyInputWhenFocusTarget(false);
        jPanel12.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, -10, 340, 60));

        labBackA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Back.png"))); // NOI18N
        labBackA3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labBackA3MouseClicked(evt);
            }
        });
        jPanel12.add(labBackA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));

        jLabel72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hupdate.png"))); // NOI18N
        jLabel72.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel72MouseClicked(evt);
            }
        });
        jPanel12.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 0, -1, 50));

        jPanel11.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1080, 50));

        Page3.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 70));

        btnFinish3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnFinish3.setForeground(new java.awt.Color(102, 0, 0));
        btnFinish3.setText("Finish");
        btnFinish3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFinish3MouseClicked(evt);
            }
        });
        btnFinish3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinish3ActionPerformed(evt);
            }
        });
        Page3.add(btnFinish3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 640, 100, -1));

        btnAdd3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnAdd3.setForeground(new java.awt.Color(102, 0, 0));
        btnAdd3.setText("Add");
        btnAdd3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdd3MouseClicked(evt);
            }
        });
        btnAdd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd3ActionPerformed(evt);
            }
        });
        Page3.add(btnAdd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 640, 100, -1));

        btnClear3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnClear3.setForeground(new java.awt.Color(102, 0, 0));
        btnClear3.setText("Clear");
        btnClear3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClear3MouseClicked(evt);
            }
        });
        btnClear3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear3ActionPerformed(evt);
            }
        });
        Page3.add(btnClear3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 640, 100, -1));

        getContentPane().add(Page3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdoIslumAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoIslumAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoIslumAActionPerformed

    private void rdoMaleAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoMaleAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoMaleAActionPerformed

    private void rdoOtherAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoOtherAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoOtherAActionPerformed

    private void rdoChristianAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoChristianAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoChristianAActionPerformed

    private void rdoHinduAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoHinduAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoHinduAActionPerformed

    private void rdoBuddishAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoBuddishAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoBuddishAActionPerformed

    private void rdoMyanmarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoMyanmarAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoMyanmarAActionPerformed

    private void labBackA1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labBackA1MouseClicked
        new StdFirstPage_View_IT().setVisible(true);
    }//GEN-LAST:event_labBackA1MouseClicked

    private void txtstdPhnoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstdPhnoAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstdPhnoAActionPerformed

    private void txtstdEmailAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstdEmailAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstdEmailAActionPerformed

    private void txtstdTeleAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstdTeleAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstdTeleAActionPerformed

    private void txtstdIdAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstdIdAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstdIdAActionPerformed

    private void txtstdNRCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstdNRCAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstdNRCAActionPerformed

    private void txtstdNameAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstdNameAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstdNameAActionPerformed

    private void btnNext1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNext1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNext1MouseClicked

    private void btnNext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext1ActionPerformed
         boolean ch=InputCheck();
         
				if(ch==true){
			    String name=txtstdNameA.getText().trim();
                            String std_no=txtstdIdA.getText();
			    Date d= new Date(DateChA.getDate().getTime());	    
		           String gender = null;
                          if (rdoMaleA.isSelected()) {
                           gender = "Male";
                              } else if (rdoFemaleA.isSelected()) {
                              gender = "Female";
                               }

                          String religion = null;
                          if (rdoBuddishA.isSelected()) {
                          religion = "Buddish";
                          } else if (rdoChristianA.isSelected()) {
                          religion = "Christian";
                          } else if (rdoHinduA.isSelected()) {
                          religion = "Hindu";
                          }else if(rdoIslumA.isSelected())
			    religion="Islum";
		            String pno=txtstdPhnoA.getText();
		            String tno=txtstdTeleA.getText();
			    String email=txtstdEmailA.getText();
                            // String nr=combNRC.getSelectedItem().toString();
                            
			    String nation=null;
			    if(rdoMyanmarA.isSelected()){
			    nation="Myanmar";
                            }else if(rdoOtherA.isSelected())
			    nation="Other";
                            //String photo=jLabelPhotoA.getText();
                            String nrc=txtstdNRCA.getText();
                             String image=txtimage.getText();
                            
                                     Student std;
            std=new Student(0,std_no,name,d,email,pno,gender,religion,nation,tno,nrc,image);
               // Address adds=new Address (rg,cty,twn);
                    StudentDAO stdao=new StudentDAO();
                   // AddressDAO addao=new AddressDAO();
                 
                  int choice=JOptionPane.showConfirmDialog(null, "Do you really want to save your data","Confrim Message",JOptionPane.INFORMATION_MESSAGE);
		          if(choice==JOptionPane.YES_OPTION) {
                  
                              stdao.addStudent(std,image);
                              //addao.addAddress(adds);
                              
                   }  
         Page1.setVisible(false);
        Page2.setVisible(true);
        Page3.setVisible(false);
        loadtableRs();
             }


    }//GEN-LAST:event_btnNext1ActionPerformed

    private void btnClear1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClear1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClear1MouseClicked

    private void btnClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear1ActionPerformed
        // TODO add your handling code here:
        txtstdNameA.setText("");
        DateChA.setDate(null);
        btngGender.clearSelection();
        txtstdNRCA.setText("");
        btngReli.clearSelection();
        btngNation.clearSelection();
        txtstdPhnoA.setText("");
        txtstdIdA.setText("");
        txtstdEmailA.setText("");
        jphoto.setIcon(null);
    }//GEN-LAST:event_btnClear1ActionPerformed

    private void labBackA3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labBackA3MouseClicked
        Page1.setVisible(false);
        Page2.setVisible(true);
        Page3.setVisible(false);
    }//GEN-LAST:event_labBackA3MouseClicked

    private void txtOrgA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrgA3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrgA3ActionPerformed

    private void txtDipoNameA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDipoNameA3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDipoNameA3ActionPerformed

    private void btnAdd3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdd3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdd3MouseClicked

    private void btnAdd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd3ActionPerformed
        int stdid=0;
         try{
             
			    String d=txtDipoNameA3.getText().trim();
		            String f=txtFieldA3.getText();
                            String o=txtOrgA3.getText();
		            String t=cboDipoTypeA3.getSelectedItem().toString();
			    Date fd=new Date(DateChFromA3.getDate().getTime());
                            Date td=new Date(jDateChooser2.getDate().getTime());
                            
			  stdid=getStudentID();
                            
 
               Qualification qua=new Qualification(0,stdid,d,f,o,t,fd,td);
               
                    QualificationDAO quadao=new QualificationDAO();
                    
                 
                  int choice=JOptionPane.showConfirmDialog(null, "Do you really want to save your data","Confrim Message",JOptionPane.INFORMATION_MESSAGE);
		          if(choice==JOptionPane.YES_OPTION) 
                   quadao.addQualification(qua);
                               loadtablQua();
                                                           
                    } catch (SQLException ex) {
         Logger.getLogger(ITstdadd.class.getName()).log(Level.SEVERE, null, ex);
     }          
                  
    }//GEN-LAST:event_btnAdd3ActionPerformed

    private void btnFinish3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinish3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFinish3MouseClicked

    private void btnFinish3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinish3ActionPerformed
        // TODO add your handling code here:
//        int choice=JOptionPane.showConfirmDialog(null,"Are you really sure to finish your add data!!!","Confirm Message",JOptionPane.INFORMATION_MESSAGE);
//        if(choice==JOptionPane.YES_OPTION){
            new StdFirstPage_View_IT().setVisible(true);
    
//        }
    }//GEN-LAST:event_btnFinish3ActionPerformed

    private void btnClear3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClear3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClear3MouseClicked

    private void btnClear3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear3ActionPerformed
        // TODO add your handling code here:
         txtDipoNameA3.setText(null);
        txtFieldA3.setText(null);
        cboDipoTypeA3.setSelectedIndex(0);
        txtOrgA3.setText(null);
        DateChFromA3.setDate(null);
        jDateChooser2.setDate(null);
    }//GEN-LAST:event_btnClear3ActionPerformed

    private void txtPhnoRsA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhnoRsA2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhnoRsA2ActionPerformed

    private void txtTownshipA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTownshipA2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTownshipA2ActionPerformed

    private void btnAdd2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdd2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdd2MouseClicked

    private void btnAdd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd2ActionPerformed
       boolean ch=InputCheckforRSnAdd();
         
				if(ch==true){
        try{
        int stdid=0;
			    String n=txtRSNameA2.getText().trim();
		            String pno=txtPhnoRsA2.getText();
		            String occup=txtAreaOccuA2.getText();
                            String rsType=cboRSTypeA2.getSelectedItem().toString();
                            
                            String r=txtRegionA2.getText();
			    String c=txtCityA2.getText();
			    String t=txtTownshipA2.getText();
			    
                    
                stdid=getStudentID();
               Relationship rsp=new Relationship(0,stdid,n,pno,occup,rsType);
               Address add=new Address (0,stdid,r,c,t);
                    RelationshipDAO rspdao=new RelationshipDAO();
                    AddressDAO addao=new AddressDAO();
                       
                    rspdao.addRelationship(rsp);
                    addao.addAddress(add);
                    loadtableRs();
           } catch (SQLException ex) {
         Logger.getLogger(ITstdadd.class.getName()).log(Level.SEVERE, null, ex);
     }
         }

        
    }//GEN-LAST:event_btnAdd2ActionPerformed

    private void btnClear2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClear2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClear2MouseClicked

    private void btnClear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear2ActionPerformed
        // TODO add your handling code here:
         txtRSNameA2.setText(null);
            txtPhnoRsA2.setText(null);
            txtAreaOccuA2.setText(null);
            cboRSTypeA2.setSelectedIndex(0);
            txtRegionA2.setText(null);
            txtCityA2.setText(null);
            txtTownshipA2.setText(null);
    }//GEN-LAST:event_btnClear2ActionPerformed

    private void labBackA2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labBackA2MouseClicked
       
        Page1.setVisible(true);
        Page2.setVisible(false);
        Page3.setVisible(false);
    }//GEN-LAST:event_labBackA2MouseClicked

    private void btnNext2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNext2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNext2MouseClicked

    private void btnNext2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext2ActionPerformed
        Page1.setVisible(false);
        Page2.setVisible(false);
        Page3.setVisible(true);
        loadtablQua();
    }//GEN-LAST:event_btnNext2ActionPerformed

    private void txtFieldA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldA3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldA3ActionPerformed

    private void txtRSNameA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRSNameA2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRSNameA2ActionPerformed

    private void txtRegionA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegionA2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegionA2ActionPerformed

    private void txtCityA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityA2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityA2ActionPerformed

    private void txtstdEmailAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtstdEmailAKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtstdEmailAKeyTyped

    private void txtstdPhnoAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtstdPhnoAKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_txtstdPhnoAKeyTyped

    private void txtstdTeleAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtstdTeleAKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_txtstdTeleAKeyTyped

    private void rdoFemaleAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoFemaleAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoFemaleAActionPerformed

    private void jfilechoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfilechoseActionPerformed
            JFileChooser fileChooser = new JFileChooser();
                int option = fileChooser.showOpenDialog(null);
                if (option == JFileChooser.APPROVE_OPTION) {
                    File selectedFile = fileChooser.getSelectedFile();
                    txtimage.setText(selectedFile.getAbsolutePath());
                    displaySelectedImage(selectedFile);
                }
    }//GEN-LAST:event_jfilechoseActionPerformed

    private void jLabel72MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel72MouseClicked
         dispose();
        AdminPanel ad = new AdminPanel();
             ad.setVisible(true);
             ad.loginPane.setVisible(false);
             ad.logoutpane.setVisible(false);
    }//GEN-LAST:event_jLabel72MouseClicked

    private void jLabel73MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel73MouseClicked
         dispose();
        AdminPanel ad = new AdminPanel();
             ad.setVisible(true);
             ad.loginPane.setVisible(false);
             ad.logoutpane.setVisible(false);
    }//GEN-LAST:event_jLabel73MouseClicked

    private void labHomeA1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labHomeA1MouseClicked
             dispose();
        AdminPanel ad = new AdminPanel();
             ad.setVisible(true);
             ad.loginPane.setVisible(false);
             ad.logoutpane.setVisible(false);
    }//GEN-LAST:event_labHomeA1MouseClicked

    private void cboDipoTypeA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDipoTypeA3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDipoTypeA3ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
       Page2.setVisible(true);
       Page1.setVisible(false);
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ITstdadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ITstdadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ITstdadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ITstdadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ITstdadd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateChA;
    private com.toedter.calendar.JDateChooser DateChFromA3;
    private javax.swing.JPanel Page1;
    private javax.swing.JPanel Page2;
    private javax.swing.JPanel Page3;
    private javax.swing.JButton btnAdd2;
    private javax.swing.JButton btnAdd3;
    private javax.swing.JButton btnClear1;
    private javax.swing.JButton btnClear2;
    private javax.swing.JButton btnClear3;
    private javax.swing.JButton btnFinish3;
    private javax.swing.JButton btnNext1;
    private javax.swing.JButton btnNext2;
    private javax.swing.ButtonGroup btngGender;
    private javax.swing.ButtonGroup btngNation;
    private javax.swing.ButtonGroup btngReli;
    private java.awt.Button button1;
    private javax.swing.JComboBox<String> cboDipoTypeA3;
    private javax.swing.JComboBox<String> cboRSTypeA2;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableEDUA3;
    private javax.swing.JTable jTableRsA;
    private javax.swing.JButton jfilechose;
    private javax.swing.JLabel jphoto;
    private javax.swing.JScrollPane jscrolEDUA3;
    private javax.swing.JScrollPane jscrolRsA;
    private javax.swing.JLabel labBackA1;
    private javax.swing.JLabel labBackA2;
    private javax.swing.JLabel labBackA3;
    private javax.swing.JLabel labHomeA1;
    private javax.swing.JRadioButton rdoBuddishA;
    private javax.swing.JRadioButton rdoChristianA;
    private javax.swing.JRadioButton rdoFemaleA;
    private javax.swing.JRadioButton rdoHinduA;
    private javax.swing.JRadioButton rdoIslumA;
    private javax.swing.JRadioButton rdoMaleA;
    private javax.swing.JRadioButton rdoMyanmarA;
    private javax.swing.JRadioButton rdoOtherA;
    private javax.swing.JTextArea txtAreaOccuA2;
    private javax.swing.JTextField txtCityA2;
    private javax.swing.JTextField txtDipoNameA3;
    private javax.swing.JTextField txtFieldA3;
    private javax.swing.JTextField txtOrgA3;
    private javax.swing.JTextField txtPhnoRsA2;
    private javax.swing.JTextField txtRSNameA2;
    private javax.swing.JTextField txtRegionA2;
    private javax.swing.JTextField txtTownshipA2;
    public javax.swing.JTextField txtimage;
    private javax.swing.JTextField txtstdEmailA;
    private javax.swing.JTextField txtstdIdA;
    private javax.swing.JTextField txtstdNRCA;
    private javax.swing.JTextField txtstdNameA;
    private javax.swing.JTextField txtstdPhnoA;
    private javax.swing.JTextField txtstdTeleA;
    // End of variables declaration//GEN-END:variables

    private boolean InputCheck() {
        boolean result = false;
        if(txtstdIdA.getText().isEmpty()){
        JOptionPane.showMessageDialog(null,"Student ID is Require!!!","Input Missing!!!",JOptionPane.ERROR_MESSAGE);
        txtstdIdA.requestFocus();
        }else{
            String stdidPattern = "(IT|JP)-Std\\d{4}";
        String stdid = txtstdIdA.getText().trim();
          
        if (!stdid.matches(stdidPattern)) {
            JOptionPane.showMessageDialog(null, "Student ID Number should start with IT-Std0001", "Invalid Student ID Number", JOptionPane.ERROR_MESSAGE);
           txtstdIdA.requestFocus();
        } else {
            String stdno = txtstdIdA.getText().trim();
             if(new StudentDAO().isStdNoExist(stdno)){
                  JOptionPane.showMessageDialog(this, "This Student No. is already exists","Student ID existing",JOptionPane.ERROR_MESSAGE);
                  txtstdIdA.requestFocus();
             }else {
	if(txtstdNameA.getText().isEmpty( )){
		JOptionPane.showMessageDialog(null,"Name is Require!!!","Input Missing!!!",JOptionPane.ERROR_MESSAGE);
		txtstdNameA.requestFocus();
            } else{
            if(DateChA.getDate()==null){
            JOptionPane.showMessageDialog(null, "Date Of Birth is required data","Input Missing Error",JOptionPane.ERROR_MESSAGE);
		} else{
                if (txtstdNRCA.getText().isEmpty()) {
                      JOptionPane.showMessageDialog(null, "NRC input is required!", "Input Missing", JOptionPane.ERROR_MESSAGE);
                      txtstdNRCA.requestFocus();
                       }
                       else{
                    String nrcPattern = "\\d{2}/[A-Za-z]+\\(N\\)\\d{6}";
                  String nrc = txtstdNRCA.getText().trim();
          
              if (!nrc.matches(nrcPattern)) {
                 JOptionPane.showMessageDialog(null, "NRC ID Number should be 12/AhSaNa(N)726123", "Invalid NRC ID Number", JOptionPane.ERROR_MESSAGE);
                txtstdNRCA.requestFocus();
                  } else {
                    
                     if(txtstdEmailA.getText().isEmpty()){
			      JOptionPane.showMessageDialog(null,"Put your email address!!!","Input Missing!!!",JOptionPane.ERROR_MESSAGE);
			      txtstdEmailA.requestFocus();
                               }else{
                          String emailPattern = ".*@gmail\\.com$";
                          String email = txtstdEmailA.getText().trim();
          
                     if (!email.matches(emailPattern)) {
                    JOptionPane.showMessageDialog(null, "Email must be end with @gmail.com", "Invalid Email", JOptionPane.ERROR_MESSAGE);
                   txtstdEmailA.requestFocus();
                      } else {
                          if(txtstdTeleA.getText().isEmpty()){
			         JOptionPane.showMessageDialog(null,"Telegram No. is Require!!!","Input Missing!!!",JOptionPane.ERROR_MESSAGE);
				txtstdTeleA.requestFocus();
                                  }else{
                              String tephnoPattern = "\\d{11}";  
                               String tephno = txtstdTeleA.getText().trim();
          
                             if (! tephno.matches(tephnoPattern)) {
                             JOptionPane.showMessageDialog(null, "Telegram Number must be only 11 digit", "Invalid Telegram Number", JOptionPane.ERROR_MESSAGE);
                           txtstdTeleA.requestFocus();
                          } else {
                             if(txtstdPhnoA.getText().isEmpty()){
			         JOptionPane.showMessageDialog(null,"Phone No. is Require!!!","Input Missing!!!",JOptionPane.ERROR_MESSAGE);
				txtstdPhnoA.requestFocus();
                                 }else{
		    if(!rdoMaleA.isSelected() && !rdoFemaleA.isSelected()){
	              JOptionPane.showMessageDialog(null, "Gender is required data","Input Missing Error",JOptionPane.ERROR_MESSAGE);
	                        }else{
                         if (!rdoBuddishA.isSelected() && !rdoChristianA.isSelected() && !rdoHinduA.isSelected() && !rdoIslumA.isSelected()) {    			  
       			 JOptionPane.showMessageDialog(this, "Please select an Religion option.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                                }else{
                              if (!rdoMyanmarA.isSelected() && !rdoOtherA.isSelected()) {
       			    JOptionPane.showMessageDialog(this, "Please select an Nationality option.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
                           }else{
		            return true; 
		            }
			  }
			}
		      }
                    }
                 }
               }
             }
           }
          }	
         }
       }
      }
     }
        }return result;
    }
    public boolean InputCheckforRSnAdd(){
          boolean result=false;
                                if(txtRSNameA2.getText().isEmpty()){
                                    JOptionPane.showMessageDialog(null, "Name is required data","Input Missing Error",JOptionPane.ERROR_MESSAGE);
                                 txtRSNameA2.requestFocus();
                                }else{
                                    if(txtPhnoRsA2.getText().isEmpty()){
                                        JOptionPane.showMessageDialog(null, "Phone Number is required data","Input Missing Error",JOptionPane.ERROR_MESSAGE);
                                        txtPhnoRsA2.requestFocus();
                                    }else{
//                                        if(txtPhnoRsA2.getText().isEmpty()){
//			         JOptionPane.showMessageDialog(null,"Phone No. is Require!!!","Input Missing!!!",JOptionPane.ERROR_MESSAGE);
//				  txtPhnoRsA2.requestFocus();
//                                 }else{
                                        if(txtAreaOccuA2.getText().isEmpty()){
                                    JOptionPane.showMessageDialog(null, "Occupation is required data","Input Missing Error",JOptionPane.ERROR_MESSAGE);
                                 txtAreaOccuA2.requestFocus();
                                        }else
                                            if(txtRegionA2.getText().isEmpty()){
                                    JOptionPane.showMessageDialog(null, "Region is required data","Input Missing Error",JOptionPane.ERROR_MESSAGE);
                                 txtRegionA2.requestFocus();
                                }else{
                                    if(txtCityA2.getText().isEmpty()){
                                        JOptionPane.showMessageDialog(null, "City is required data","Input Missing Error",JOptionPane.ERROR_MESSAGE);
                                    txtCityA2.requestFocus();
                                    }else{
                                        if(txtTownshipA2.getText().isEmpty()){
			         JOptionPane.showMessageDialog(null,"Township is Require!!!","Input Missing!!!",JOptionPane.ERROR_MESSAGE);
				  txtTownshipA2.requestFocus();
                                        }else 
                                            return true;
                                    }
                                }
                             }
                           }
//                         }
                       
                           
        return result;
    }
    
     
    
     public void loadAllDataintoTableRS(ArrayList<Relationship>list){
        
        DefaultTableModel dtm=(DefaultTableModel) jTableRsA.getModel();
        dtm.setRowCount(0);
        
        for(Relationship rs :list){
            Vector v=new Vector();
            
            v.add(rs.getName());
            v.add(rs.getPhno());
            v.add(rs.getOccupation());
            v.add(rs.getRs_type());

            dtm.addRow(v);
            
        } 
      }
        public void loadtableRs(){
            
            RelationshipDAO rsdao=new RelationshipDAO();
            ArrayList list=rsdao.loaddataRS();
            loadAllDataintoTableRS(list);
        }
        
         public void loadAllDataintoTableQua(ArrayList<Qualification>list){
        
        DefaultTableModel dtm=(DefaultTableModel) jTableEDUA3.getModel();
        dtm.setRowCount(0);
        
        for(Qualification qua :list){
            Vector v=new Vector();
            v.add(qua.getDip_name());
            v.add(qua.getField_name());
            v.add(qua.getType());
	    v.add(qua.getOrg_name());
	    v.add(qua.getFrom_date());
	    v.add(qua.getTo_date());
            

            dtm.addRow(v);
            
        } 
      } 
        public void loadtablQua(){
            
            QualificationDAO quadao=new QualificationDAO();
            ArrayList list=quadao.loaddataQua();
            loadAllDataintoTableQua(list);
        }
          public int getStudentID() throws SQLException{
            int id=0;
            String maxId = "SELECT MAX(std_id) FROM student";
            
            PreparedStatement statement = con.prepareStatement(maxId);
            ResultSet rs = statement.executeQuery();
            
            
            while (rs.next()) {
                id = rs.getInt(1);
                
            }
             return id;
        }
        
             public void displaySelectedImage(File selectedFile) {
        try {
            Image image = ImageIO.read(selectedFile);
            if (image != null) {
                // Resize the image to fit the JLabel
                Image resizedImage = image.getScaledInstance(jphoto.getWidth(),
                        jphoto.getHeight(), Image.SCALE_SMOOTH);
               jphoto.setIcon(new ImageIcon(resizedImage));
            } else {
                jphoto.setIcon(null);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
       
  

}
