/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ITStudent;

import AdminLogin.AdminPanel;
import java.awt.Image;
import java.awt.event.MouseEvent;
import java.sql.Date;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author User
 */
public class StdFirstPage_View_IT extends javax.swing.JFrame {

    /**
     * Creates new form ITStudentdata
     */
    public StdFirstPage_View_IT() {
        initComponents();
         Image ic=new ImageIcon(this.getClass().getResource("/jpro.jpg")).getImage();
        this.setIconImage(ic);
        loadtable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EDUBack = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        labHomeVEDU = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        labBackVEDU = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEduV = new javax.swing.JTable();
        ITstdMainPane = new javax.swing.JPanel();
        btnViewStd = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labBack = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ItStdInfo = new javax.swing.JScrollPane();
        jTableItStd = new javax.swing.JTable();
        btnAddStd = new javax.swing.JButton();
        btnUpdateStd = new javax.swing.JButton();
        txtSearchStd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        StdView = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtstdNationaityV = new javax.swing.JTextField();
        txtstdGenderV = new javax.swing.JTextField();
        txtstdReligionV = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        labHomeV = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labBackVs = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtstdPhnoV = new javax.swing.JTextField();
        txtstdEmailV = new javax.swing.JTextField();
        txtstdTeleV = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtstdIdV = new javax.swing.JTextField();
        DateChV = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        txtstdNRCV = new javax.swing.JTextField();
        txtstdNameV = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lblvimg = new javax.swing.JLabel();
        txtImagePath = new javax.swing.JTextField();
        txtviewstd = new javax.swing.JTextField();
        labEduBackV = new javax.swing.JLabel();
        labMoreDetailV = new javax.swing.JLabel();
        MoreDetail = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        labHomeVMd = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        labBackVMd = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jscrolRsV = new javax.swing.JScrollPane();
        jTableRsV = new javax.swing.JTable();
        jPanel16 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        txtTownshipV = new javax.swing.JTextField();
        txtRegionV = new javax.swing.JTextField();
        txtCityV = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JPRO InfoHub Course Management System");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EDUBack.setBackground(new java.awt.Color(204, 204, 204));
        EDUBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        EDUBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setBackground(new java.awt.Color(153, 0, 0));
        jPanel17.setMinimumSize(new java.awt.Dimension(1100, 65));
        jPanel17.setPreferredSize(new java.awt.Dimension(1200, 65));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel18.setBackground(new java.awt.Color(204, 204, 204));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labHomeVEDU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hupdate.png"))); // NOI18N
        labHomeVEDU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labHomeVEDUMouseClicked(evt);
            }
        });
        jPanel18.add(labHomeVEDU, new org.netbeans.lib.awtextra.AbsoluteConstraints(1024, 0, 60, -1));

        jLabel33.setBackground(new java.awt.Color(204, 0, 0));
        jLabel33.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(204, 0, 0));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Education Background");
        jLabel33.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel33.setVerifyInputWhenFocusTarget(false);
        jPanel18.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 390, 50));

        labBackVEDU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Back.png"))); // NOI18N
        labBackVEDU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labBackVEDUMouseClicked(evt);
            }
        });
        jPanel18.add(labBackVEDU, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jPanel17.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1080, 50));

        EDUBack.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 70));

        jTableEduV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Diploma_Name", "Field_Name", "Type", "Org_Name", "From_date", "To_date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableEduV);

        EDUBack.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 1000, 450));

        getContentPane().add(EDUBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 690));

        ITstdMainPane.setBackground(new java.awt.Color(204, 204, 204));
        ITstdMainPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        ITstdMainPane.setMinimumSize(new java.awt.Dimension(1100, 690));
        ITstdMainPane.setPreferredSize(new java.awt.Dimension(1100, 690));
        ITstdMainPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewStd.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnViewStd.setText("View");
        btnViewStd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewStdMouseClicked(evt);
            }
        });
        btnViewStd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewStdActionPerformed(evt);
            }
        });
        ITstdMainPane.add(btnViewStd, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 620, 120, 40));

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));
        jPanel2.setMinimumSize(new java.awt.Dimension(1100, 65));
        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 65));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 0, 0));
        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("IT's Student Info");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 340, 50));

        labBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labBackMouseClicked(evt);
            }
        });
        jPanel1.add(labBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hupdate.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 0, 60, 50));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 50));

        ITstdMainPane.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 70));

        jTableItStd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Std_ID", "Std_No", "Student_Name", "DOB", "Email", "Ph_NO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableItStd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableItStdMouseClicked(evt);
            }
        });
        ItStdInfo.setViewportView(jTableItStd);

        ITstdMainPane.add(ItStdInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 1000, 450));

        btnAddStd.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnAddStd.setText("ADD");
        btnAddStd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddStdMouseClicked(evt);
            }
        });
        btnAddStd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStdActionPerformed(evt);
            }
        });
        ITstdMainPane.add(btnAddStd, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 620, 120, 40));

        btnUpdateStd.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnUpdateStd.setText("Update");
        btnUpdateStd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateStdMouseClicked(evt);
            }
        });
        btnUpdateStd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStdActionPerformed(evt);
            }
        });
        ITstdMainPane.add(btnUpdateStd, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 620, 120, 40));

        txtSearchStd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSearchStd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchStdActionPerformed(evt);
            }
        });
        txtSearchStd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchStdKeyReleased(evt);
            }
        });
        ITstdMainPane.add(txtSearchStd, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, 190, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/searchp.png"))); // NOI18N
        ITstdMainPane.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 110, 40, 30));
        ITstdMainPane.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 110, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Sync30px-removebg-preview.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        ITstdMainPane.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(995, 105, 40, 40));

        getContentPane().add(ITstdMainPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 690));
        ITstdMainPane.getAccessibleContext().setAccessibleDescription("");
        MoreDetail.setVisible(false);
        EDUBack.setVisible(false);
        StdView.setVisible(false);

        StdView.setBackground(new java.awt.Color(204, 204, 204));
        StdView.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        StdView.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setBackground(new java.awt.Color(153, 153, 153));
        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(153, 0, 0));
        jLabel29.setText("General Info");
        jPanel10.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 40));

        StdView.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, 120, -1));

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 0, 0));
        jLabel15.setText("Nationality");
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 90, 20));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 0, 0));
        jLabel18.setText("Gender");
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 80, 20));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 0, 0));
        jLabel19.setText("Religion");
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 80, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 0));
        jLabel8.setText(":");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 10, 20));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 0, 0));
        jLabel25.setText(":");
        jPanel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 10, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 0, 0));
        jLabel26.setText(":");
        jPanel7.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 10, -1));

        txtstdNationaityV.setEditable(false);
        txtstdNationaityV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtstdNationaityV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstdNationaityVActionPerformed(evt);
            }
        });
        jPanel7.add(txtstdNationaityV, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 210, -1));

        txtstdGenderV.setEditable(false);
        txtstdGenderV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtstdGenderV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstdGenderVActionPerformed(evt);
            }
        });
        jPanel7.add(txtstdGenderV, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 210, -1));

        txtstdReligionV.setEditable(false);
        txtstdReligionV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtstdReligionV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstdReligionVActionPerformed(evt);
            }
        });
        jPanel7.add(txtstdReligionV, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 210, -1));

        StdView.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, 520, 230));

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setBackground(new java.awt.Color(153, 153, 153));
        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(153, 0, 0));
        jLabel28.setText("Contact Info");
        jPanel8.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 40));

        StdView.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 120, 30));

        jPanel4.setBackground(new java.awt.Color(153, 0, 0));
        jPanel4.setMinimumSize(new java.awt.Dimension(1100, 65));
        jPanel4.setPreferredSize(new java.awt.Dimension(1200, 65));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labHomeV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hupdate.png"))); // NOI18N
        labHomeV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labHomeVMouseClicked(evt);
            }
        });
        jPanel5.add(labHomeV, new org.netbeans.lib.awtextra.AbsoluteConstraints(1024, 0, 60, -1));

        jLabel6.setBackground(new java.awt.Color(204, 0, 0));
        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Student's Info");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.setVerifyInputWhenFocusTarget(false);
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, -8, 340, -1));

        labBackVs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Back.png"))); // NOI18N
        labBackVs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labBackVsMouseClicked(evt);
            }
        });
        jPanel5.add(labBackVs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1080, 50));

        StdView.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 70));

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 0, 0));
        jLabel14.setText("Phone No");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 140, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 0, 0));
        jLabel16.setText("Telegram No");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 150, -1));

        txtstdPhnoV.setEditable(false);
        txtstdPhnoV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtstdPhnoV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstdPhnoVActionPerformed(evt);
            }
        });
        jPanel6.add(txtstdPhnoV, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 210, -1));

        txtstdEmailV.setEditable(false);
        txtstdEmailV.setBackground(new java.awt.Color(255, 255, 255));
        txtstdEmailV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtstdEmailV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstdEmailVActionPerformed(evt);
            }
        });
        jPanel6.add(txtstdEmailV, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 210, -1));

        txtstdTeleV.setEditable(false);
        txtstdTeleV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtstdTeleV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstdTeleVActionPerformed(evt);
            }
        });
        jPanel6.add(txtstdTeleV, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 210, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 0, 0));
        jLabel22.setText(":");
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 20, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 0, 0));
        jLabel23.setText(":");
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 20, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 0, 0));
        jLabel24.setText(":");
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 20, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(102, 0, 0));
        jLabel30.setText("Email No");
        jPanel6.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 140, -1));

        StdView.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 480, 230));

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(153, 153, 153));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 0, 0));
        jLabel11.setText("Basic Info");
        jPanel9.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 20));

        StdView.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 100, 40));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 0));
        jLabel7.setText("Date of birth");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 150, -1));

        txtstdIdV.setEditable(false);
        txtstdIdV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtstdIdV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstdIdVActionPerformed(evt);
            }
        });
        jPanel3.add(txtstdIdV, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 210, -1));
        jPanel3.add(DateChV, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 210, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 0));
        jLabel10.setText("Student's ID  ");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 140, -1));

        txtstdNRCV.setEditable(false);
        txtstdNRCV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtstdNRCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstdNRCVActionPerformed(evt);
            }
        });
        jPanel3.add(txtstdNRCV, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 210, -1));

        txtstdNameV.setEditable(false);
        txtstdNameV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtstdNameV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstdNameVActionPerformed(evt);
            }
        });
        jPanel3.add(txtstdNameV, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 210, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 0));
        jLabel9.setText("Student's Name  ");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 140, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 0, 0));
        jLabel12.setText(":");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 20, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 0, 0));
        jLabel13.setText(":");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 20, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 0, 0));
        jLabel20.setText(":");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 20, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 0, 0));
        jLabel21.setText(":");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 20, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 0, 0));
        jLabel27.setText("NRC No");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 130, -1));

        lblvimg.setForeground(new java.awt.Color(255, 51, 51));
        lblvimg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(lblvimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 230, 200));

        txtImagePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImagePathActionPerformed(evt);
            }
        });
        jPanel3.add(txtImagePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 50, 20));
        jPanel3.add(txtviewstd, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 90, 20));

        StdView.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 1030, 260));

        labEduBackV.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labEduBackV.setForeground(new java.awt.Color(153, 0, 0));
        labEduBackV.setText("        Education Background");
        labEduBackV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        labEduBackV.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        labEduBackV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labEduBackV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labEduBackVMouseClicked(evt);
            }
        });
        StdView.add(labEduBackV, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 640, 240, 30));

        labMoreDetailV.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labMoreDetailV.setForeground(new java.awt.Color(153, 0, 0));
        labMoreDetailV.setText("         More Detail");
        labMoreDetailV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        labMoreDetailV.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        labMoreDetailV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labMoreDetailV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labMoreDetailVMouseClicked(evt);
            }
        });
        StdView.add(labMoreDetailV, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 640, 160, 30));

        getContentPane().add(StdView, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 690));

        MoreDetail.setBackground(new java.awt.Color(204, 204, 204));
        MoreDetail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        MoreDetail.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBackground(new java.awt.Color(204, 204, 204));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setBackground(new java.awt.Color(153, 153, 153));
        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(153, 0, 0));
        jLabel31.setText("Relationship");
        jPanel15.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        MoreDetail.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 110, 30));

        jPanel11.setBackground(new java.awt.Color(153, 0, 0));
        jPanel11.setMinimumSize(new java.awt.Dimension(1100, 65));
        jPanel11.setPreferredSize(new java.awt.Dimension(1200, 65));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(204, 204, 204));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labHomeVMd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hupdate.png"))); // NOI18N
        labHomeVMd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labHomeVMdMouseClicked(evt);
            }
        });
        jPanel12.add(labHomeVMd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 0, 60, -1));

        jLabel17.setBackground(new java.awt.Color(204, 0, 0));
        jLabel17.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Student's More Detail");
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel17.setVerifyInputWhenFocusTarget(false);
        jPanel12.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 360, 50));

        labBackVMd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Back.png"))); // NOI18N
        labBackVMd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labBackVMdMouseClicked(evt);
            }
        });
        jPanel12.add(labBackVMd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jPanel11.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1080, 50));

        MoreDetail.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 70));

        jPanel13.setBackground(new java.awt.Color(204, 204, 204));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableRsV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Ph_NO", "Occupation", "Rs_Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jscrolRsV.setViewportView(jTableRsV);

        jPanel13.add(jscrolRsV, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 980, 290));

        MoreDetail.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 1020, 330));

        jPanel16.setBackground(new java.awt.Color(204, 204, 204));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setBackground(new java.awt.Color(153, 153, 153));
        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(153, 0, 0));
        jLabel32.setText("Address");
        jPanel16.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        MoreDetail.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 90, 30));

        jPanel19.setBackground(new java.awt.Color(204, 204, 204));
        jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel52.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(102, 0, 0));
        jLabel52.setText("Region");
        jPanel19.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 70, -1));

        jLabel53.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(102, 0, 0));
        jLabel53.setText(":");
        jPanel19.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 10, -1));

        jLabel54.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(102, 0, 0));
        jLabel54.setText("City");
        jPanel19.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 30, -1));

        jLabel55.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(102, 0, 0));
        jLabel55.setText(":");
        jPanel19.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 20, -1));

        jLabel56.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(102, 0, 0));
        jLabel56.setText("Township");
        jPanel19.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 80, -1));

        jLabel57.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(102, 0, 0));
        jLabel57.setText(":");
        jPanel19.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, 20, -1));

        txtTownshipV.setEditable(false);
        txtTownshipV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTownshipV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTownshipVActionPerformed(evt);
            }
        });
        jPanel19.add(txtTownshipV, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, 230, -1));

        txtRegionV.setEditable(false);
        txtRegionV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtRegionV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegionVActionPerformed(evt);
            }
        });
        jPanel19.add(txtRegionV, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 230, -1));

        txtCityV.setEditable(false);
        txtCityV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCityV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityVActionPerformed(evt);
            }
        });
        jPanel19.add(txtCityV, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 230, -1));

        MoreDetail.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 1020, 110));

        getContentPane().add(MoreDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 690));
        EDUBack.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labBackMouseClicked
        AdminLogin.AdminPanel ad = new AdminLogin.AdminPanel();
        ad.pChoose.setVisible(true);
    }//GEN-LAST:event_labBackMouseClicked

    private void btnViewStdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewStdMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewStdMouseClicked

    private void btnViewStdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewStdActionPerformed

        index = jTableItStd.getSelectedRow();

            if(index<0){
               JOptionPane.showMessageDialog(null, "Please select any record from table for View");
            }else
            {    
            txtviewstd.setVisible(false);
            ITstdMainPane.setVisible(false);
            StdView.setVisible(true);
           MoreDetail.setVisible(false);
           EDUBack.setVisible(false);
           txtImagePath.setVisible(false);
                 row_id=(int)jTableItStd.getValueAt(index, 0);
        StudentDAO sdao=new StudentDAO();
        Student sc=sdao.returnAllDataToTextfieldStd(row_id);

        txtstdNameV.setText(sc.getName());
        txtstdIdV.setText(sc.getStd_no());
        DateChV.setDate(sc.getDob());
        txtstdNRCV.setText(sc.getNrc());
        txtstdEmailV.setText(sc.getEmail());
        txtstdTeleV.setText(sc.getTele_no());
        txtstdPhnoV.setText(sc.getPhno());
        txtstdGenderV.setText(sc.getGender());
        txtstdReligionV.setText(sc.getReligion());
        txtstdNationaityV.setText(sc.getNation());
        txtviewstd.setText(String.valueOf(sc.getStd_id()));
        String filePath = sc.getPhoto();
                txtImagePath.setText(filePath);
                ImageIcon imageIcon = new ImageIcon(filePath);
                  lblvimg.setIcon(imageIcon);
                    
        
            }
        
        
    }//GEN-LAST:event_btnViewStdActionPerformed

    private void btnAddStdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddStdMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddStdMouseClicked

    private void btnAddStdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStdActionPerformed
        ITstdadd itadd=new ITstdadd();
          itadd.setVisible(true);
          itadd.txtimage.setVisible(false);
    }//GEN-LAST:event_btnAddStdActionPerformed

    private void btnUpdateStdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateStdMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateStdMouseClicked
 int index = 0;
 int row_id=0;
    private void btnUpdateStdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStdActionPerformed
            
            index = jTableItStd.getSelectedRow();

            if(index<0){
               JOptionPane.showMessageDialog(null, "Please select any record from table for update");
            }else
            {       
                   ITstdUpdate up=new ITstdUpdate();
                    up.setVisible(true);
                    up.txtstd_id.setVisible(false);
                    up.txtimgpath.setVisible(false);
                 row_id=(int)jTableItStd.getValueAt(index, 0);
                
                StudentDAO  sdao=new StudentDAO();
                Student  std=sdao.returnAllDataToTextfieldStd(row_id); 
                up.txtstd_id.setText(String.valueOf(std.getStd_id()));
                up.txtstdIdU.setText(std.getStd_no());
                up.txtstdNameU.setText(std.getName());
                up.txtdateu.setDate(std.getDob());
                up.txtstdNRCU.setText(std.getNrc());
                up.txtstdEmailU.setText(std.getEmail());
                up.txtstdTeleU.setText(std.getTele_no());
                up.txtstdPhnoU.setText(std.getPhno());
                String gender = std.getGender();
                  if (gender.equals("Male")) {
                    up.rdoMaleU.setSelected(true);
                   } else if (gender.equals("Female")) {
                    up.rdoFemaleU.setSelected(true);
                          }
                   String religion = std.getReligion();
                   if(religion.equals("Buddish")){
                   up.rdoBuddishU.setSelected(true);
                   }else if(religion.equals("Christian")){
                   up.rdoChristianU.setSelected(true);
                   }else if(religion.equals("Hindu")){
                   up.rdoHinduU.setSelected(true);
                   }else if(religion.equals("Islam")){
                   up.rdoIslumU.setSelected(true);
                       }

                     String nation=std.getNation();
                     if(nation.equals("Myanmar")){
                     up.rdoMyanmarU.setSelected(true);
                     }else if(nation.equals("Others")){
                     up.rdoOtherU.setSelected(true);
            }
                String filePath = std.getPhoto();
                up.txtimgpath.setText(filePath);
                ImageIcon imageIcon = new ImageIcon(filePath);
                  up.lblupdateimg.setIcon(imageIcon);
                
            }
    }//GEN-LAST:event_btnUpdateStdActionPerformed

    private void txtSearchStdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchStdActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtSearchStdActionPerformed

    private void labBackVsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labBackVsMouseClicked
        ITstdMainPane.setVisible(true);
        loadtable();
        StdView.setVisible(false);
        MoreDetail.setVisible(false);
        EDUBack.setVisible(false);
    }//GEN-LAST:event_labBackVsMouseClicked

    private void txtstdIdVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstdIdVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstdIdVActionPerformed

    private void txtstdPhnoVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstdPhnoVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstdPhnoVActionPerformed

    private void txtstdNRCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstdNRCVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstdNRCVActionPerformed

    private void txtstdNameVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstdNameVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstdNameVActionPerformed

    private void txtstdEmailVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstdEmailVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstdEmailVActionPerformed

    private void txtstdTeleVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstdTeleVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstdTeleVActionPerformed

    private void labBackVMdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labBackVMdMouseClicked
        ITstdMainPane.setVisible(false);
        StdView.setVisible(true);
        MoreDetail.setVisible(false);
        EDUBack.setVisible(false);
    }//GEN-LAST:event_labBackVMdMouseClicked

    private void labBackVEDUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labBackVEDUMouseClicked
        ITstdMainPane.setVisible(false);
        StdView.setVisible(true);
        MoreDetail.setVisible(false);
        EDUBack.setVisible(false);
    }//GEN-LAST:event_labBackVEDUMouseClicked

    private void labMoreDetailVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labMoreDetailVMouseClicked
          int idview=Integer.parseInt(txtviewstd.getText());    
        ITstdMainPane.setVisible(false);
        StdView.setVisible(false);
        MoreDetail.setVisible(true);
        EDUBack.setVisible(false);
             RelationshipDAO rsdao=new RelationshipDAO();
            ArrayList list=rsdao.loadupdatedataRS(idview);
            loadAllDataintoTableRS(list);
            AddressDAO ado=new AddressDAO();
            Address add=new Address();
         add=ado.returnAllDataToTextfieldAdd(idview);
         txtRegionV.setText(add.getRegion());
         txtCityV.setText(add.getCity());
         txtTownshipV.setText(add.getTown());
            
    }//GEN-LAST:event_labMoreDetailVMouseClicked

    private void labEduBackVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labEduBackVMouseClicked
        int idv=Integer.parseInt(txtviewstd.getText());
        ITstdMainPane.setVisible(false);
        StdView.setVisible(false);
        MoreDetail.setVisible(false);
        EDUBack.setVisible(true);
        QualificationDAO qao=new QualificationDAO();
        ArrayList list=qao.loadUpdatedataQua(idv);
        loadAllDataintoTableQua(list);
        
    }//GEN-LAST:event_labEduBackVMouseClicked

    private void txtTownshipVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTownshipVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTownshipVActionPerformed

    private void txtRegionVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegionVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegionVActionPerformed

    private void txtCityVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityVActionPerformed

    private void jTableItStdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableItStdMouseClicked
        // TODO add your handling code here:
//        jTableItStd.addMouseListener(new java.awt.event.MouseAdapter() {
// public void mouseClicked(java.awt.event.MouseEvent evt){
//jTableItStdMouseClicked(evt);
//}
//});      
  
    }//GEN-LAST:event_jTableItStdMouseClicked

    private void txtSearchStdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchStdKeyReleased
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel)jTableItStd.getModel();
                  TableRowSorter<DefaultTableModel>tr= new TableRowSorter<DefaultTableModel>(model);
                  jTableItStd.setRowSorter(tr);
                  tr.setRowFilter(RowFilter.regexFilter(txtSearchStd.getText()));
    }//GEN-LAST:event_txtSearchStdKeyReleased

    private void txtstdNationaityVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstdNationaityVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstdNationaityVActionPerformed

    private void txtstdGenderVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstdGenderVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstdGenderVActionPerformed

    private void txtstdReligionVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstdReligionVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstdReligionVActionPerformed

    private void txtImagePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImagePathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImagePathActionPerformed

    private void labHomeVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labHomeVMouseClicked
            dispose();
        AdminPanel ad = new AdminPanel();
             ad.setVisible(true);
             ad.loginPane.setVisible(false);
             ad.logoutpane.setVisible(false);
    }//GEN-LAST:event_labHomeVMouseClicked

    private void labHomeVMdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labHomeVMdMouseClicked
         dispose();  
        AdminPanel ad = new AdminPanel();
             ad.setVisible(true);
             ad.loginPane.setVisible(false);
             ad.logoutpane.setVisible(false);
    }//GEN-LAST:event_labHomeVMdMouseClicked

    private void labHomeVEDUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labHomeVEDUMouseClicked
         dispose();  
        AdminPanel ad = new AdminPanel();
             ad.setVisible(true);
             ad.loginPane.setVisible(false);
             ad.logoutpane.setVisible(false);
    }//GEN-LAST:event_labHomeVEDUMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
           dispose();
        AdminPanel ad = new AdminPanel();
             ad.setVisible(true);
             ad.loginPane.setVisible(false);
             ad.logoutpane.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
       
        txtSearchStd.setText(null);
        DefaultTableModel model = (DefaultTableModel)jTableItStd.getModel();
        TableRowSorter<DefaultTableModel>tr= new TableRowSorter<DefaultTableModel>(model);
        jTableItStd.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(txtSearchStd.getText()));
        loadtable();
        
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StdFirstPage_View_IT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StdFirstPage_View_IT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StdFirstPage_View_IT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StdFirstPage_View_IT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StdFirstPage_View_IT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateChV;
    private javax.swing.JPanel EDUBack;
    private javax.swing.JPanel ITstdMainPane;
    private javax.swing.JScrollPane ItStdInfo;
    private javax.swing.JPanel MoreDetail;
    private javax.swing.JPanel StdView;
    private javax.swing.JButton btnAddStd;
    private javax.swing.JButton btnUpdateStd;
    private javax.swing.JButton btnViewStd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEduV;
    public javax.swing.JTable jTableItStd;
    private javax.swing.JTable jTableRsV;
    private javax.swing.JScrollPane jscrolRsV;
    private javax.swing.JLabel labBack;
    private javax.swing.JLabel labBackVEDU;
    private javax.swing.JLabel labBackVMd;
    private javax.swing.JLabel labBackVs;
    private javax.swing.JLabel labEduBackV;
    private javax.swing.JLabel labHomeV;
    private javax.swing.JLabel labHomeVEDU;
    private javax.swing.JLabel labHomeVMd;
    private javax.swing.JLabel labMoreDetailV;
    private javax.swing.JLabel lblvimg;
    private javax.swing.JTextField txtCityV;
    private javax.swing.JTextField txtImagePath;
    private javax.swing.JTextField txtRegionV;
    private javax.swing.JTextField txtSearchStd;
    private javax.swing.JTextField txtTownshipV;
    private javax.swing.JTextField txtstdEmailV;
    private javax.swing.JTextField txtstdGenderV;
    private javax.swing.JTextField txtstdIdV;
    private javax.swing.JTextField txtstdNRCV;
    private javax.swing.JTextField txtstdNameV;
    private javax.swing.JTextField txtstdNationaityV;
    private javax.swing.JTextField txtstdPhnoV;
    private javax.swing.JTextField txtstdReligionV;
    private javax.swing.JTextField txtstdTeleV;
    private javax.swing.JTextField txtviewstd;
    // End of variables declaration//GEN-END:variables

 public void loadAllDataintoTable(ArrayList<Student>list){
        
        DefaultTableModel dtm=(DefaultTableModel) jTableItStd.getModel();
        dtm.setRowCount(0);
        
        for(Student std :list){
            Vector v=new Vector();
	    v.add(std.getStd_id());
            v.add(std.getStd_no());
            v.add(std.getName());
            v.add(std.getDob());
            v.add(std.getEmail());
	    v.add(std.getPhno());
            

            dtm.addRow(v);
            
        } 
      }
        public void loadtable(){
            
            StudentDAO stdao=new StudentDAO();
            ArrayList list=stdao.loaddataStd();
            loadAllDataintoTable(list);
        }
        
         public void loadAllDataintoTableRS(ArrayList<Relationship>list){
        
        DefaultTableModel dtm=(DefaultTableModel) jTableRsV.getModel();
        dtm.setRowCount(0);
        
        for(Relationship rs :list){
            Vector v=new Vector();
            
            v.add(rs.getName());
            v.add(rs.getPhno());
            v.add(rs.getOccupation());
	    
            v.add(rs.getRs_type());

            dtm.addRow(v);
            
        } 
      }
        public void loadtableRs(){
            
            RelationshipDAO rsdao=new RelationshipDAO();
            ArrayList list=rsdao.loaddataRS();
            loadAllDataintoTable(list);
        }
        
         public void loadAllDataintoTableQua(ArrayList<Qualification>list){
        
        DefaultTableModel dtm=(DefaultTableModel) jTableEduV.getModel();
        dtm.setRowCount(0);
        
        for(Qualification qua :list){
            Vector v=new Vector();
            v.add(qua.getDip_name());
            v.add(qua.getField_name());
            v.add(qua.getType());
	    v.add(qua.getOrg_name());
	    v.add(qua.getFrom_date());
	    v.add(qua.getTo_date());
            

            dtm.addRow(v);
            
        } 
      } 
        public void loadtableQua(){
            
            QualificationDAO quadao=new QualificationDAO();
            ArrayList list=quadao.loaddataQua();
            loadAllDataintoTable(list);
        }
        
     
        
        
}
