/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Course;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import AdminLogin.AdminPanel;
import java.awt.Image;
import javax.swing.ImageIcon;


/**
 *
 * @author shoto
 */
public class Course extends javax.swing.JFrame {
 Connection conn=null;
ResultSet rs=null;
PreparedStatement pst=null;
    /**
     * Creates new form Course
     */
    public Course() {
        initComponents();
         Image ic=new ImageIcon(this.getClass().getResource("/jpro.jpg")).getImage();
        this.setIconImage(ic);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblidcall = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtcDu = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablecourse = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        txtcName = new javax.swing.JTextField();
        txtcsearch = new javax.swing.JTextField();
        txtcFees = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        txtcNo = new javax.swing.JTextField();
        txtupcno = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txcID = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtcDesc = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JPRO InfoHub Course Management System");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(1100, 70));
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 70));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hupdate.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 0, -1, 50));

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 45)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Course Information");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, -1, 50));
        jPanel3.add(lblidcall, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 60, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1080, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 70));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        jPanel2.setMinimumSize(new java.awt.Dimension(1100, 630));
        jPanel2.setPreferredSize(new java.awt.Dimension(1090, 630));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtcDu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtcDu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcDuActionPerformed(evt);
            }
        });
        jPanel2.add(txtcDu, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 230, 30));

        jTablecourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Course Id", "Course No", "Course Name", "Duration", "Course Fees", "Description"
            }
        ));
        jTablecourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablecourseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablecourse);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 700, 520));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/search.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, 30, 40));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(102, 0, 0));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 100, 40));

        btnView.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnView.setForeground(new java.awt.Color(102, 0, 0));
        btnView.setText("Clear");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        jPanel2.add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 530, 100, 40));

        txtcName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtcName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcNameActionPerformed(evt);
            }
        });
        jPanel2.add(txtcName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 230, 30));

        txtcsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcsearchActionPerformed(evt);
            }
        });
        txtcsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcsearchKeyReleased(evt);
            }
        });
        jPanel2.add(txtcsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 250, 30));

        txtcFees.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtcFees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcFeesActionPerformed(evt);
            }
        });
        jPanel2.add(txtcFees, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 230, 30));

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(102, 0, 0));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, 100, 40));

        txtcNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtcNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcNoActionPerformed(evt);
            }
        });
        jPanel2.add(txtcNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 230, 30));

        txtupcno.setEditable(false);
        txtupcno.setBackground(new java.awt.Color(204, 204, 204));
        txtupcno.setText("jTextField1");
        jPanel2.add(txtupcno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 230, -1));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setForeground(new java.awt.Color(204, 204, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 0));
        jLabel3.setText("Enter Course Data");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 160, 60));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0), 3));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setText("Course No");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 0));
        jLabel5.setText("Course Name");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 0));
        jLabel6.setText("Duration");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 0));
        jLabel7.setText("Course Fees");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 0));
        jLabel4.setText("Description");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, 30));

        jLabel67.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 0, 51));
        jLabel67.setText("*");
        jPanel4.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 20, 20));

        jLabel68.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 0, 51));
        jLabel68.setText("*");
        jPanel4.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 20, 20));

        jLabel69.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 0, 51));
        jLabel69.setText("*");
        jPanel4.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 20, 20));

        jLabel70.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 0, 51));
        jLabel70.setText("*");
        jPanel4.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 20, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 0, 0));
        jLabel13.setText(":");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 20, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 0, 0));
        jLabel12.setText(":");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 10, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 0));
        jLabel10.setText(":");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 10, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 0, 0));
        jLabel14.setText(":");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 10, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 0, 0));
        jLabel15.setText(":");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 20, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 0, 0));
        jLabel11.setText(":");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 20, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 0, 0));
        jLabel17.setText("Course Id");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        txcID.setEditable(false);
        txcID.setBackground(new java.awt.Color(204, 204, 204));
        txcID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txcIDActionPerformed(evt);
            }
        });
        jPanel4.add(txcID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 230, 30));

        txtcDesc.setColumns(20);
        txtcDesc.setRows(5);
        jScrollPane4.setViewportView(txtcDesc);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 230, 110));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 370, 450));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Sync30px-removebg-preview.png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 10, -1, 35));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1100, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcDuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcDuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcDuActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
//        loadcoursetable();
            txcID.setVisible(true);
            txcID.setText("");
            txtcNo.setVisible(true);
             txtcNo.setText("");
             txtcName.setText("");
             txtcDu.setText("");
             txtcFees.setText(String.valueOf(""));
             txtcDesc.setText("");
    }//GEN-LAST:event_btnViewActionPerformed

    private void txtcNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcNameActionPerformed

    private void txtcFeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcFeesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcFeesActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
      txtcNo.setVisible(true);
 
        try {
        
         boolean ch=inputCheck();
         if(ch==true){
             String no=txtcNo.getText();
             String name=txtcName.getText();
             String cdesc=txtcDesc.getText();
             String cdu=txtcDu.getText();
             int cfees = Integer.parseInt(txtcFees.getText());
             Course_Class cc=new Course_Class(0,no,name,cdesc,cdu,cfees);
             CourseDAO cdao=new CourseDAO();
             
             int choice=JOptionPane.showConfirmDialog(null, "Do you really want to save your data","Confirm Message",JOptionPane.INFORMATION_MESSAGE);
             if(choice==JOptionPane.YES_OPTION)
            
             cdao.insert_course(cc);
             loadcoursetable();
             
             txtcNo.setText("");
             txtcName.setText("");
             txtcDu.setText("");
             txtcFees.setText(String.valueOf(""));
             txtcDesc.setText("");
         }
        
     } catch (SQLException ex) {
         Logger.getLogger(Course.class.getName()).log(Level.SEVERE, null, ex);
     }
     

    }//GEN-LAST:event_btnAddActionPerformed
    int id=0;
    private void jTablecourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablecourseMouseClicked
         txtcNo.setVisible(false);
        txtupcno.setVisible(true);
        int index = jTablecourse.getSelectedRow();

            if(index<0){
               JOptionPane.showMessageDialog(null, "Please select any record from table for update");
            }else
            { 
                int id=(int) jTablecourse.getValueAt(index, 0);
                CourseDAO cdao=new CourseDAO();
                Course_Class cc=cdao.returnAllDataToTextfield(id); 
                txcID.setText(String.valueOf(cc.getCid()));
                txtcNo.setText(cc.getCno());
                txtupcno.setText(cc.getCno());
                txtcName.setText(cc.getCname());
                txtcDu.setText(cc.getDu());
                txtcFees.setText(String.valueOf(cc.getFees()));
                txtcDesc.setText(cc.getCdesc());
                
            }
    }//GEN-LAST:event_jTablecourseMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        txtupcno.setVisible(true);
        int index = jTablecourse.getSelectedRow();
        if(index<0){
               JOptionPane.showMessageDialog(null, "Please select any record from table for update");
            }else
            {  
            try {
                boolean ch=inputUpdateCheck();
                if(ch==true){
                    DefaultTableModel model = (DefaultTableModel)jTablecourse.getModel();
                    
                    id = Integer.parseInt(jTablecourse.getValueAt(index, 0).toString());
                    
                    String no=txtupcno.getText();
                    String name=txtcName.getText();
                    String cdesc=txtcDesc.getText();
                    String cdu=txtcDu.getText();
                    int cfees = Integer.parseInt(txtcFees.getText());
                    Course_Class cc=new Course_Class(id,no,name,cdesc,cdu,cfees);
                    CourseDAO cdao=new CourseDAO();
                    int choice=JOptionPane.showConfirmDialog(null, "Do you really want to save your data","Confirm Message",JOptionPane.INFORMATION_MESSAGE);
                    if(choice==JOptionPane.YES_OPTION)
                        cdao.updateCourse_Data(cc);
                    loadcoursetable();
                    txtupcno.setText("");
                    txtcName.setText("");
                    txtcDu.setText("");
                    txtcFees.setText(String.valueOf(""));
                    txtcDesc.setText("");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Course.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtcsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcsearchKeyReleased
        DefaultTableModel model = (DefaultTableModel)jTablecourse.getModel();
                  TableRowSorter<DefaultTableModel>tr= new TableRowSorter<DefaultTableModel>(model);
                  jTablecourse.setRowSorter(tr);
                  tr.setRowFilter(RowFilter.regexFilter(txtcsearch.getText())); 

    }//GEN-LAST:event_txtcsearchKeyReleased

    private void txtcsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcsearchActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        dispose();
        AdminPanel ad = new AdminPanel();
             ad.setVisible(true);
             ad.loginPane.setVisible(false);
             ad.logoutpane.setVisible(false);
         
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        DefaultTableModel RecordTable = (DefaultTableModel) jTablecourse.getModel();
        TableRowSorter<DefaultTableModel>tr= new TableRowSorter<DefaultTableModel>(RecordTable);
        jTablecourse.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(txtcsearch.getText()));
    }//GEN-LAST:event_jLabel8MouseClicked

    private void txtcNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcNoActionPerformed

    private void txcIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txcIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txcIDActionPerformed

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        txtcsearch.setText(null);
        DefaultTableModel model = (DefaultTableModel)jTablecourse.getModel();
        TableRowSorter<DefaultTableModel>tr= new TableRowSorter<DefaultTableModel>(model);
        jTablecourse.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(txtcsearch.getText()));
        loadcoursetable();

    }//GEN-LAST:event_jLabel18MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Course().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTablecourse;
    public javax.swing.JLabel lblidcall;
    private javax.swing.JTextField txcID;
    private javax.swing.JTextArea txtcDesc;
    private javax.swing.JTextField txtcDu;
    private javax.swing.JTextField txtcFees;
    private javax.swing.JTextField txtcName;
    private javax.swing.JTextField txtcNo;
    private javax.swing.JTextField txtcsearch;
    private javax.swing.JTextField txtupcno;
    // End of variables declaration//GEN-END:variables



    public boolean inputCheck() throws SQLException {
    boolean result = false;

    if (txtcNo.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Course No is required data", "Input Missing Error", JOptionPane.ERROR_MESSAGE);
        txtcNo.requestFocus();
    } else {
        String cnoPattern = "^(JP|IT)-Course\\d+$";
        String courseNo = txtcNo.getText().trim();
          
        if (!courseNo.matches(cnoPattern)) {
            JOptionPane.showMessageDialog(null, "Course Number should start with JP-Course1 or IT-Course1", "Invalid Course Number", JOptionPane.ERROR_MESSAGE);
           txtcNo.requestFocus();
        } else {
            String cno = txtcNo.getText().trim();
             if(new CourseDAO().isCourseNoExist(cno)){
                  JOptionPane.showMessageDialog(this, "This Course No. is already exists");
                  txtcNo.requestFocus();
             }else {
//                if (txtcName.getText().isEmpty()) {
//                    JOptionPane.showMessageDialog(null, "Course Name is required data", "Input Missing Error", JOptionPane.ERROR_MESSAGE);
//                } else {
//                    String cnamePattern = "^[A-Za-z\\-\\[A-Za-z][0-9]+$";
//                    String courseName = txtcName.getText().trim();

//                    if (!courseName.matches(cnamePattern)) {
//                        JOptionPane.showMessageDialog(null, "Course Name should be letters only", "Invalid Course Name", JOptionPane.ERROR_MESSAGE);
//                    } else {
                            if (txtcDu.getText().isEmpty()) {
                                JOptionPane.showMessageDialog(null, "Course Duration is required data", "Input Missing Error", JOptionPane.ERROR_MESSAGE);
                            } else {
                                String cduPattern = "^\\d+\\s*(years?|months?)\\s*((\\d+\\s*months?)|(\\d+\\s*years?))?";
                                String duration = txtcDu.getText().trim();

                                if (!duration.matches(cduPattern)) {
                                    JOptionPane.showMessageDialog(null, "Duration must include year(s) or month(s)", "Invalid Course Duration", JOptionPane.ERROR_MESSAGE);
                                } else {
                                    if (txtcFees.getText().isEmpty()) {
                                        JOptionPane.showMessageDialog(null, "Course Fees is required data", "Input Missing Error", JOptionPane.ERROR_MESSAGE);
                                    } else {
                                        String cdescPattern = "\\d+";
                                        String fees = txtcFees.getText().trim();

                                        if (!fees.matches(cdescPattern)) {
                                            JOptionPane.showMessageDialog(null, "Course Fees must be numeric", "Invalid Course Fees", JOptionPane.ERROR_MESSAGE);
                                        } else {
                                            if (txtcDesc.getText().isEmpty()) {
                                                JOptionPane.showMessageDialog(null, "Course Description is required data", "Input Missing Error", JOptionPane.ERROR_MESSAGE);
                                            } else {
                                                result = true;
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
//            }
//    }
    
    return result;
}
        
       public boolean inputUpdateCheck() throws SQLException {
    boolean result = false;

//    if (txtcNo.getText().isEmpty()) {
//        JOptionPane.showMessageDialog(null, "Course No is required data", "Input Missing Error", JOptionPane.ERROR_MESSAGE);
//        txtcNo.requestFocus();
//    } else {
//        String cnoPattern = "^(JP|IP|FE)-\\d+$";
//        String courseNo = txtcNo.getText().trim();
//
//        if (!courseNo.matches(cnoPattern)) {
//            JOptionPane.showMessageDialog(null, "Course Number should start with JP-, IP-, or FE-", "Invalid Course Number", JOptionPane.ERROR_MESSAGE);
//        } else {
                if (txtcName.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Course Name is required data", "Input Missing Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    String cnamePattern = "^[A-Za-z\\-\\'\\s]+$";
                    String courseName = txtcName.getText().trim();

                    if (!courseName.matches(cnamePattern)) {
                        JOptionPane.showMessageDialog(null, "Course Name should be letters only", "Invalid Course Name", JOptionPane.ERROR_MESSAGE);
                    } else {
                            if (txtcDu.getText().isEmpty()) {
                                JOptionPane.showMessageDialog(null, "Course Duration is required data", "Input Missing Error", JOptionPane.ERROR_MESSAGE);
                            } else {
                                String cduPattern = "^\\d+\\s*(years?|months?)\\s*((\\d+\\s*months?)|(\\d+\\s*years?))?";
                                String duration = txtcDu.getText().trim();

                                if (!duration.matches(cduPattern)) {
                                    JOptionPane.showMessageDialog(null, "Duration must include year(s) or month(s)", "Invalid Course Duration", JOptionPane.ERROR_MESSAGE);
                                } else {
                                    if (txtcFees.getText().isEmpty()) {
                                        JOptionPane.showMessageDialog(null, "Course Fees is required data", "Input Missing Error", JOptionPane.ERROR_MESSAGE);
                                    } else {
                                        String cdescPattern = "\\d+";
                                        String fees = txtcFees.getText().trim();

                                        if (!fees.matches(cdescPattern)) {
                                            JOptionPane.showMessageDialog(null, "Course Fees must be numeric", "Invalid Course Fees", JOptionPane.ERROR_MESSAGE);
                                        } else {
                                            if (txtcDesc.getText().isEmpty()) {
                                                JOptionPane.showMessageDialog(null, "Course Description is required data", "Input Missing Error", JOptionPane.ERROR_MESSAGE);
                                            } else {
                                                result = true;
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                
            
    
    
    return result;
}

          public void loadAllCourseDataintoTable(ArrayList<Course_Class>list){
        
        DefaultTableModel dtm=(DefaultTableModel) jTablecourse.getModel();
        dtm.setRowCount(0);
        
        for(Course_Class cc :list){
            Vector v=new Vector();
            v.add(cc.getCid());
            v.add(cc.getCno());
            v.add(cc.getCname());
            v.add(cc.getDu());
            v.add(cc.getFees());
            v.add(cc.getCdesc());
            dtm.addRow(v);
            
        } 
      }
  
        
        
     
        public void loadcoursetable(){
            
            CourseDAO cdao=new CourseDAO();
            ArrayList list1=cdao.loadCoursedata();
            loadAllCourseDataintoTable(list1);

        }


}
